{{- if not .Values.media.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gojellyfin.mediaClaimName" . }}
  labels:
    {{- include "gojellyfin.labels" (dict "root" $ "component" "media") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.media.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.media.persistence.accessModes | nindent 4 }}
  {{- with .Values.media.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.media.persistence.size }}
{{- end }}
