
// Code generated by ent, DO NOT EDIT.



	

package plugin




import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/FreekingDean/gojellyfin/internal/store/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)


const (
	// Label holds the string label denoting the plugin type in the database.
	Label = "plugin"
		// FieldID holds the string denoting the id field in the database.
		FieldID = "id"
		// FieldCreatedAt holds the string denoting the created_at field in the database.
		FieldCreatedAt = "created_at"
		// FieldUpdatedAt holds the string denoting the updated_at field in the database.
		FieldUpdatedAt = "updated_at"
		// FieldName holds the string denoting the name field in the database.
		FieldName = "name"
		// FieldVersion holds the string denoting the version field in the database.
		FieldVersion = "version"
		// FieldDescription holds the string denoting the description field in the database.
		FieldDescription = "description"
		// FieldConfigurationFileName holds the string denoting the configuration_file_name field in the database.
		FieldConfigurationFileName = "configuration_file_name"
		// FieldStatus holds the string denoting the status field in the database.
		FieldStatus = "status"
		// FieldCanUninstall holds the string denoting the can_uninstall field in the database.
		FieldCanUninstall = "can_uninstall"
		// FieldHasImage holds the string denoting the has_image field in the database.
		FieldHasImage = "has_image"
	// Table holds the table name of the plugin in the database.
	Table = "plugins"

)



	
	// Columns holds all SQL columns for plugin fields.
	var Columns = []string{
			FieldID,
				FieldCreatedAt,
				FieldUpdatedAt,
				FieldName,
				FieldVersion,
				FieldDescription,
				FieldConfigurationFileName,
				FieldStatus,
				FieldCanUninstall,
				FieldHasImage,
	}
	
	

	





	
// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}









	var (
				// DefaultCreatedAt holds the default value on creation for the "created_at" field.
				DefaultCreatedAt func() time.Time
				// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
				DefaultUpdatedAt func() time.Time
				// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
				UpdateDefaultUpdatedAt func() time.Time
	)




	
	
	
		
		
		// Status defines the type for the "status" enum field.
		type Status string

		// Status values.
		const (
				StatusActive Status = "Active"
				StatusRestart Status = "Restart"
				StatusDeleted Status = "Deleted"
				StatusSuperceded Status = "Superceded"
				StatusMalfunctioned Status = "Malfunctioned"
				StatusNotSupported Status = "NotSupported"
				StatusDisabled Status = "Disabled"
		)

		func (s Status) String() string {
			return string(s)
		}
	


	
	// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
	func StatusValidator(s Status) error {
		switch s {
			case StatusActive,StatusRestart,StatusDeleted,StatusSuperceded,StatusMalfunctioned,StatusNotSupported,StatusDisabled:
				return nil
			default:
				return fmt.Errorf("plugin: invalid enum value for status field: %q", s)
		}
	}



// OrderOption defines the ordering options for the Plugin queries.
type OrderOption func(*sql.Selector)

	
	
		// ByID orders the results by the id field.
		func ByID(opts ...sql.OrderTermOption) OrderOption {
			return sql.OrderByField(FieldID, opts...).ToFunc()
		}
	
			// ByCreatedAt orders the results by the created_at field.
			func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
			}
			// ByUpdatedAt orders the results by the updated_at field.
			func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
			}
			// ByName orders the results by the name field.
			func ByName(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldName, opts...).ToFunc()
			}
			// ByVersion orders the results by the version field.
			func ByVersion(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldVersion, opts...).ToFunc()
			}
			// ByDescription orders the results by the description field.
			func ByDescription(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldDescription, opts...).ToFunc()
			}
			// ByConfigurationFileName orders the results by the configuration_file_name field.
			func ByConfigurationFileName(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldConfigurationFileName, opts...).ToFunc()
			}
			// ByStatus orders the results by the status field.
			func ByStatus(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldStatus, opts...).ToFunc()
			}
			// ByCanUninstall orders the results by the can_uninstall field.
			func ByCanUninstall(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldCanUninstall, opts...).ToFunc()
			}
			// ByHasImage orders the results by the has_image field.
			func ByHasImage(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldHasImage, opts...).ToFunc()
			}







