// Code generated by ent, DO NOT EDIT.

package trickplay

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the trickplay type in the database.
	Label = "trickplay"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldTileWidth holds the string denoting the tile_width field in the database.
	FieldTileWidth = "tile_width"
	// FieldTileHeight holds the string denoting the tile_height field in the database.
	FieldTileHeight = "tile_height"
	// FieldThumbnailCount holds the string denoting the thumbnail_count field in the database.
	FieldThumbnailCount = "thumbnail_count"
	// FieldInterval holds the string denoting the interval field in the database.
	FieldInterval = "interval"
	// FieldBandwidth holds the string denoting the bandwidth field in the database.
	FieldBandwidth = "bandwidth"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// Table holds the table name of the trickplay in the database.
	Table = "trickplays"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "trickplays"
	// ItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemInverseTable = "items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "item_trickplays"
)

// Columns holds all SQL columns for trickplay fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldWidth,
	FieldHeight,
	FieldTileWidth,
	FieldTileHeight,
	FieldThumbnailCount,
	FieldInterval,
	FieldBandwidth,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "trickplays"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"item_trickplays",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Trickplay queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByTileWidth orders the results by the tile_width field.
func ByTileWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTileWidth, opts...).ToFunc()
}

// ByTileHeight orders the results by the tile_height field.
func ByTileHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTileHeight, opts...).ToFunc()
}

// ByThumbnailCount orders the results by the thumbnail_count field.
func ByThumbnailCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailCount, opts...).ToFunc()
}

// ByInterval orders the results by the interval field.
func ByInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterval, opts...).ToFunc()
}

// ByBandwidth orders the results by the bandwidth field.
func ByBandwidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBandwidth, opts...).ToFunc()
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
