package server

import (
	"go.uber.org/fx"

	"github.com/FreekingDean/gojellyfin/internal/scanner"
	"github.com/FreekingDean/gojellyfin/internal/server/activitylog"
	"github.com/FreekingDean/gojellyfin/internal/server/apikey"
	"github.com/FreekingDean/gojellyfin/internal/server/branding"
	"github.com/FreekingDean/gojellyfin/internal/server/channels"
	"github.com/FreekingDean/gojellyfin/internal/server/configuration"
	"github.com/FreekingDean/gojellyfin/internal/server/dashboard"
	"github.com/FreekingDean/gojellyfin/internal/server/devices"
	"github.com/FreekingDean/gojellyfin/internal/server/displaypreferences"
	"github.com/FreekingDean/gojellyfin/internal/server/environment"
	"github.com/FreekingDean/gojellyfin/internal/server/filter"
	"github.com/FreekingDean/gojellyfin/internal/server/genres"
	"github.com/FreekingDean/gojellyfin/internal/server/image"
	"github.com/FreekingDean/gojellyfin/internal/server/items"
	"github.com/FreekingDean/gojellyfin/internal/server/itemupdate"
	"github.com/FreekingDean/gojellyfin/internal/server/library"
	"github.com/FreekingDean/gojellyfin/internal/server/librarystructure"
	"github.com/FreekingDean/gojellyfin/internal/server/livetv"
	"github.com/FreekingDean/gojellyfin/internal/server/localization"
	"github.com/FreekingDean/gojellyfin/internal/server/mediainfo"
	"github.com/FreekingDean/gojellyfin/internal/server/packages"
	"github.com/FreekingDean/gojellyfin/internal/server/persons"
	"github.com/FreekingDean/gojellyfin/internal/server/playlists"
	"github.com/FreekingDean/gojellyfin/internal/server/playstate"
	"github.com/FreekingDean/gojellyfin/internal/server/plugins"
	"github.com/FreekingDean/gojellyfin/internal/server/quickconnect"
	"github.com/FreekingDean/gojellyfin/internal/server/scheduledtasks"
	"github.com/FreekingDean/gojellyfin/internal/server/search"
	"github.com/FreekingDean/gojellyfin/internal/server/session"
	"github.com/FreekingDean/gojellyfin/internal/server/studios"
	"github.com/FreekingDean/gojellyfin/internal/server/subtitle"
	"github.com/FreekingDean/gojellyfin/internal/server/suggestions"
	"github.com/FreekingDean/gojellyfin/internal/server/syncplay"
	"github.com/FreekingDean/gojellyfin/internal/server/system"
	"github.com/FreekingDean/gojellyfin/internal/server/timesync"
	"github.com/FreekingDean/gojellyfin/internal/server/trailers"
	"github.com/FreekingDean/gojellyfin/internal/server/tvshows"
	"github.com/FreekingDean/gojellyfin/internal/server/user"
	"github.com/FreekingDean/gojellyfin/internal/server/userlibrary"
	"github.com/FreekingDean/gojellyfin/internal/server/userviews"
	"github.com/FreekingDean/gojellyfin/internal/server/years"
	"github.com/FreekingDean/gojellyfin/internal/tasks"
)

var Module = fx.Module(
	"server",
	activitylog.Module,
	apikey.Module,
	branding.Module,
	channels.Module,
	configuration.Module,
	dashboard.Module,
	devices.Module,
	displaypreferences.Module,
	environment.Module,
	filter.Module,
	genres.Module,
	image.Module,
	items.Module,
	itemupdate.Module,
	library.Module,
	librarystructure.Module,
	livetv.Module,
	localization.Module,
	mediainfo.Module,
	packages.Module,
	persons.Module,
	playlists.Module,
	playstate.Module,
	plugins.Module,
	quickconnect.Module,
	scheduledtasks.Module,
	search.Module,
	session.Module,
	studios.Module,
	subtitle.Module,
	suggestions.Module,
	syncplay.Module,
	system.Module,
	timesync.Module,
	trailers.Module,
	tvshows.Module,
	user.Module,
	userlibrary.Module,
	userviews.Module,
	years.Module,
	fx.Provide(
		New,
	),
	fx.Invoke(
		useScanner,
	),
)

func useScanner(registry *tasks.Registry, scanner *scanner.Scanner) error {
	return registry.UseRunner(tasks.LibraryScanID, scanner.Scan)
}
