
// Code generated by ent, DO NOT EDIT.



	

package mediasource




import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/FreekingDean/gojellyfin/internal/store/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)


const (
	// Label holds the string label denoting the mediasource type in the database.
	Label = "media_source"
		// FieldID holds the string denoting the id field in the database.
		FieldID = "id"
		// FieldCreatedAt holds the string denoting the created_at field in the database.
		FieldCreatedAt = "created_at"
		// FieldUpdatedAt holds the string denoting the updated_at field in the database.
		FieldUpdatedAt = "updated_at"
		// FieldProtocol holds the string denoting the protocol field in the database.
		FieldProtocol = "protocol"
		// FieldEncoderProtocol holds the string denoting the encoder_protocol field in the database.
		FieldEncoderProtocol = "encoder_protocol"
		// FieldKind holds the string denoting the kind field in the database.
		FieldKind = "kind"
		// FieldTimestamp holds the string denoting the timestamp field in the database.
		FieldTimestamp = "timestamp"
		// FieldVideoType holds the string denoting the video_type field in the database.
		FieldVideoType = "video_type"
		// FieldIsoType holds the string denoting the iso_type field in the database.
		FieldIsoType = "iso_type"
		// FieldVideo3dFormat holds the string denoting the video_3d_format field in the database.
		FieldVideo3dFormat = "video_3d_format"
		// FieldName holds the string denoting the name field in the database.
		FieldName = "name"
		// FieldPath holds the string denoting the path field in the database.
		FieldPath = "path"
		// FieldEncoderPath holds the string denoting the encoder_path field in the database.
		FieldEncoderPath = "encoder_path"
		// FieldContainer holds the string denoting the container field in the database.
		FieldContainer = "container"
		// FieldSize holds the string denoting the size field in the database.
		FieldSize = "size"
		// FieldRunTimeTicks holds the string denoting the run_time_ticks field in the database.
		FieldRunTimeTicks = "run_time_ticks"
		// FieldBitrate holds the string denoting the bitrate field in the database.
		FieldBitrate = "bitrate"
		// FieldIsRemote holds the string denoting the is_remote field in the database.
		FieldIsRemote = "is_remote"
		// FieldIsInfiniteStream holds the string denoting the is_infinite_stream field in the database.
		FieldIsInfiniteStream = "is_infinite_stream"
		// FieldSupportsTranscoding holds the string denoting the supports_transcoding field in the database.
		FieldSupportsTranscoding = "supports_transcoding"
		// FieldSupportsDirectStream holds the string denoting the supports_direct_stream field in the database.
		FieldSupportsDirectStream = "supports_direct_stream"
		// FieldSupportsDirectPlay holds the string denoting the supports_direct_play field in the database.
		FieldSupportsDirectPlay = "supports_direct_play"
		// FieldSupportsProbing holds the string denoting the supports_probing field in the database.
		FieldSupportsProbing = "supports_probing"
		// FieldReadAtNativeFramerate holds the string denoting the read_at_native_framerate field in the database.
		FieldReadAtNativeFramerate = "read_at_native_framerate"
		// FieldIgnoreDts holds the string denoting the ignore_dts field in the database.
		FieldIgnoreDts = "ignore_dts"
		// FieldIgnoreIndex holds the string denoting the ignore_index field in the database.
		FieldIgnoreIndex = "ignore_index"
		// FieldGenPtsInput holds the string denoting the gen_pts_input field in the database.
		FieldGenPtsInput = "gen_pts_input"
		// FieldRequiresLooping holds the string denoting the requires_looping field in the database.
		FieldRequiresLooping = "requires_looping"
		// FieldHasSegments holds the string denoting the has_segments field in the database.
		FieldHasSegments = "has_segments"
		// FieldDefaultAudioStreamIndex holds the string denoting the default_audio_stream_index field in the database.
		FieldDefaultAudioStreamIndex = "default_audio_stream_index"
		// FieldDefaultSubtitleStreamIndex holds the string denoting the default_subtitle_stream_index field in the database.
		FieldDefaultSubtitleStreamIndex = "default_subtitle_stream_index"
		// FieldFormats holds the string denoting the formats field in the database.
		FieldFormats = "formats"
		// EdgeItem holds the string denoting the item edge name in mutations.
		EdgeItem = "item"
		// EdgeStreams holds the string denoting the streams edge name in mutations.
		EdgeStreams = "streams"
		// EdgeAttachments holds the string denoting the attachments edge name in mutations.
		EdgeAttachments = "attachments"
	// Table holds the table name of the mediasource in the database.
	Table = "media_sources"
		// ItemTable is the table that holds the item relation/edge.
		ItemTable = "media_sources"
			// ItemInverseTable is the table name for the Item entity.
			// It exists in this package in order to avoid circular dependency with the "item" package.
			ItemInverseTable = "items"
			// ItemColumn is the table column denoting the item relation/edge.
			ItemColumn = "item_media_sources"
		// StreamsTable is the table that holds the streams relation/edge.
		StreamsTable = "media_streams"
			// StreamsInverseTable is the table name for the MediaStream entity.
			// It exists in this package in order to avoid circular dependency with the "mediastream" package.
			StreamsInverseTable = "media_streams"
			// StreamsColumn is the table column denoting the streams relation/edge.
			StreamsColumn = "media_source_streams"
		// AttachmentsTable is the table that holds the attachments relation/edge.
		AttachmentsTable = "media_attachments"
			// AttachmentsInverseTable is the table name for the MediaAttachment entity.
			// It exists in this package in order to avoid circular dependency with the "mediaattachment" package.
			AttachmentsInverseTable = "media_attachments"
			// AttachmentsColumn is the table column denoting the attachments relation/edge.
			AttachmentsColumn = "media_source_attachments"

)



	
	// Columns holds all SQL columns for mediasource fields.
	var Columns = []string{
			FieldID,
				FieldCreatedAt,
				FieldUpdatedAt,
				FieldProtocol,
				FieldEncoderProtocol,
				FieldKind,
				FieldTimestamp,
				FieldVideoType,
				FieldIsoType,
				FieldVideo3dFormat,
				FieldName,
				FieldPath,
				FieldEncoderPath,
				FieldContainer,
				FieldSize,
				FieldRunTimeTicks,
				FieldBitrate,
				FieldIsRemote,
				FieldIsInfiniteStream,
				FieldSupportsTranscoding,
				FieldSupportsDirectStream,
				FieldSupportsDirectPlay,
				FieldSupportsProbing,
				FieldReadAtNativeFramerate,
				FieldIgnoreDts,
				FieldIgnoreIndex,
				FieldGenPtsInput,
				FieldRequiresLooping,
				FieldHasSegments,
				FieldDefaultAudioStreamIndex,
				FieldDefaultSubtitleStreamIndex,
				FieldFormats,
	}
	
	
		// ForeignKeys holds the SQL foreign-keys that are owned by the "media_sources"
		// table and are not defined as standalone fields in the schema.
		var ForeignKeys = []string{
				"item_media_sources",
		}
	

	





	
// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
		for i := range ForeignKeys {
			if column == ForeignKeys[i] {
				return true
			}
		}
	return false
}









	var (
				// DefaultCreatedAt holds the default value on creation for the "created_at" field.
				DefaultCreatedAt func() time.Time
				// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
				DefaultUpdatedAt func() time.Time
				// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
				UpdateDefaultUpdatedAt func() time.Time
	)




	
	
	
		
		
		// Protocol defines the type for the "protocol" enum field.
		type Protocol string

		// Protocol values.
		const (
				ProtocolFile Protocol = "File"
				ProtocolHttp Protocol = "Http"
				ProtocolRtmp Protocol = "Rtmp"
				ProtocolRtsp Protocol = "Rtsp"
				ProtocolUdp Protocol = "Udp"
				ProtocolRtp Protocol = "Rtp"
				ProtocolFtp Protocol = "Ftp"
		)

		func (pr Protocol) String() string {
			return string(pr)
		}
	


	
	// ProtocolValidator is a validator for the "protocol" field enum values. It is called by the builders before save.
	func ProtocolValidator(pr Protocol) error {
		switch pr {
			case ProtocolFile,ProtocolHttp,ProtocolRtmp,ProtocolRtsp,ProtocolUdp,ProtocolRtp,ProtocolFtp:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for protocol field: %q", pr)
		}
	}

	
	
	
		
		
		// EncoderProtocol defines the type for the "encoder_protocol" enum field.
		type EncoderProtocol string

		// EncoderProtocol values.
		const (
				EncoderProtocolFile EncoderProtocol = "File"
				EncoderProtocolHttp EncoderProtocol = "Http"
				EncoderProtocolRtmp EncoderProtocol = "Rtmp"
				EncoderProtocolRtsp EncoderProtocol = "Rtsp"
				EncoderProtocolUdp EncoderProtocol = "Udp"
				EncoderProtocolRtp EncoderProtocol = "Rtp"
				EncoderProtocolFtp EncoderProtocol = "Ftp"
		)

		func (ep EncoderProtocol) String() string {
			return string(ep)
		}
	


	
	// EncoderProtocolValidator is a validator for the "encoder_protocol" field enum values. It is called by the builders before save.
	func EncoderProtocolValidator(ep EncoderProtocol) error {
		switch ep {
			case EncoderProtocolFile,EncoderProtocolHttp,EncoderProtocolRtmp,EncoderProtocolRtsp,EncoderProtocolUdp,EncoderProtocolRtp,EncoderProtocolFtp:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for encoder_protocol field: %q", ep)
		}
	}

	
	
	
		
		
		// Kind defines the type for the "kind" enum field.
		type Kind string

		// Kind values.
		const (
				KindDefault Kind = "Default"
				KindGrouping Kind = "Grouping"
				KindPlaceholder Kind = "Placeholder"
		)

		func (k Kind) String() string {
			return string(k)
		}
	


	
	// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
	func KindValidator(k Kind) error {
		switch k {
			case KindDefault,KindGrouping,KindPlaceholder:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for kind field: %q", k)
		}
	}

	
	
	
		
		
		// Timestamp defines the type for the "timestamp" enum field.
		type Timestamp string

		// Timestamp values.
		const (
				TimestampNone Timestamp = "None"
				TimestampZero Timestamp = "Zero"
				TimestampValid Timestamp = "Valid"
		)

		func (t Timestamp) String() string {
			return string(t)
		}
	


	
	// TimestampValidator is a validator for the "timestamp" field enum values. It is called by the builders before save.
	func TimestampValidator(t Timestamp) error {
		switch t {
			case TimestampNone,TimestampZero,TimestampValid:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for timestamp field: %q", t)
		}
	}

	
	
	
		
		
		// VideoType defines the type for the "video_type" enum field.
		type VideoType string

		// VideoType values.
		const (
				VideoTypeVideoFile VideoType = "VideoFile"
				VideoTypeIso VideoType = "Iso"
				VideoTypeDvd VideoType = "Dvd"
				VideoTypeBluRay VideoType = "BluRay"
		)

		func (vt VideoType) String() string {
			return string(vt)
		}
	


	
	// VideoTypeValidator is a validator for the "video_type" field enum values. It is called by the builders before save.
	func VideoTypeValidator(vt VideoType) error {
		switch vt {
			case VideoTypeVideoFile,VideoTypeIso,VideoTypeDvd,VideoTypeBluRay:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for video_type field: %q", vt)
		}
	}

	
	
	
		
		
		// IsoType defines the type for the "iso_type" enum field.
		type IsoType string

		// IsoType values.
		const (
				IsoTypeDvd IsoType = "Dvd"
				IsoTypeBluRay IsoType = "BluRay"
		)

		func (it IsoType) String() string {
			return string(it)
		}
	


	
	// IsoTypeValidator is a validator for the "iso_type" field enum values. It is called by the builders before save.
	func IsoTypeValidator(it IsoType) error {
		switch it {
			case IsoTypeDvd,IsoTypeBluRay:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for iso_type field: %q", it)
		}
	}

	
	
	
		
		
		// Video3dFormat defines the type for the "video_3d_format" enum field.
		type Video3dFormat string

		// Video3dFormat values.
		const (
				Video3dFormatHalfSideBySide Video3dFormat = "HalfSideBySide"
				Video3dFormatFullSideBySide Video3dFormat = "FullSideBySide"
				Video3dFormatFullTopAndBottom Video3dFormat = "FullTopAndBottom"
				Video3dFormatHalfTopAndBottom Video3dFormat = "HalfTopAndBottom"
				Video3dFormatMVC Video3dFormat = "MVC"
		)

		func (v3f Video3dFormat) String() string {
			return string(v3f)
		}
	


	
	// Video3dFormatValidator is a validator for the "video_3d_format" field enum values. It is called by the builders before save.
	func Video3dFormatValidator(v3f Video3dFormat) error {
		switch v3f {
			case Video3dFormatHalfSideBySide,Video3dFormatFullSideBySide,Video3dFormatFullTopAndBottom,Video3dFormatHalfTopAndBottom,Video3dFormatMVC:
				return nil
			default:
				return fmt.Errorf("mediasource: invalid enum value for video_3d_format field: %q", v3f)
		}
	}



// OrderOption defines the ordering options for the MediaSource queries.
type OrderOption func(*sql.Selector)

	
	
		// ByID orders the results by the id field.
		func ByID(opts ...sql.OrderTermOption) OrderOption {
			return sql.OrderByField(FieldID, opts...).ToFunc()
		}
	
			// ByCreatedAt orders the results by the created_at field.
			func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
			}
			// ByUpdatedAt orders the results by the updated_at field.
			func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
			}
			// ByProtocol orders the results by the protocol field.
			func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldProtocol, opts...).ToFunc()
			}
			// ByEncoderProtocol orders the results by the encoder_protocol field.
			func ByEncoderProtocol(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldEncoderProtocol, opts...).ToFunc()
			}
			// ByKind orders the results by the kind field.
			func ByKind(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldKind, opts...).ToFunc()
			}
			// ByTimestamp orders the results by the timestamp field.
			func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
			}
			// ByVideoType orders the results by the video_type field.
			func ByVideoType(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldVideoType, opts...).ToFunc()
			}
			// ByIsoType orders the results by the iso_type field.
			func ByIsoType(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldIsoType, opts...).ToFunc()
			}
			// ByVideo3dFormat orders the results by the video_3d_format field.
			func ByVideo3dFormat(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldVideo3dFormat, opts...).ToFunc()
			}
			// ByName orders the results by the name field.
			func ByName(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldName, opts...).ToFunc()
			}
			// ByPath orders the results by the path field.
			func ByPath(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldPath, opts...).ToFunc()
			}
			// ByEncoderPath orders the results by the encoder_path field.
			func ByEncoderPath(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldEncoderPath, opts...).ToFunc()
			}
			// ByContainer orders the results by the container field.
			func ByContainer(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldContainer, opts...).ToFunc()
			}
			// BySize orders the results by the size field.
			func BySize(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSize, opts...).ToFunc()
			}
			// ByRunTimeTicks orders the results by the run_time_ticks field.
			func ByRunTimeTicks(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldRunTimeTicks, opts...).ToFunc()
			}
			// ByBitrate orders the results by the bitrate field.
			func ByBitrate(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldBitrate, opts...).ToFunc()
			}
			// ByIsRemote orders the results by the is_remote field.
			func ByIsRemote(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldIsRemote, opts...).ToFunc()
			}
			// ByIsInfiniteStream orders the results by the is_infinite_stream field.
			func ByIsInfiniteStream(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldIsInfiniteStream, opts...).ToFunc()
			}
			// BySupportsTranscoding orders the results by the supports_transcoding field.
			func BySupportsTranscoding(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSupportsTranscoding, opts...).ToFunc()
			}
			// BySupportsDirectStream orders the results by the supports_direct_stream field.
			func BySupportsDirectStream(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSupportsDirectStream, opts...).ToFunc()
			}
			// BySupportsDirectPlay orders the results by the supports_direct_play field.
			func BySupportsDirectPlay(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSupportsDirectPlay, opts...).ToFunc()
			}
			// BySupportsProbing orders the results by the supports_probing field.
			func BySupportsProbing(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSupportsProbing, opts...).ToFunc()
			}
			// ByReadAtNativeFramerate orders the results by the read_at_native_framerate field.
			func ByReadAtNativeFramerate(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldReadAtNativeFramerate, opts...).ToFunc()
			}
			// ByIgnoreDts orders the results by the ignore_dts field.
			func ByIgnoreDts(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldIgnoreDts, opts...).ToFunc()
			}
			// ByIgnoreIndex orders the results by the ignore_index field.
			func ByIgnoreIndex(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldIgnoreIndex, opts...).ToFunc()
			}
			// ByGenPtsInput orders the results by the gen_pts_input field.
			func ByGenPtsInput(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldGenPtsInput, opts...).ToFunc()
			}
			// ByRequiresLooping orders the results by the requires_looping field.
			func ByRequiresLooping(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldRequiresLooping, opts...).ToFunc()
			}
			// ByHasSegments orders the results by the has_segments field.
			func ByHasSegments(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldHasSegments, opts...).ToFunc()
			}
			// ByDefaultAudioStreamIndex orders the results by the default_audio_stream_index field.
			func ByDefaultAudioStreamIndex(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldDefaultAudioStreamIndex, opts...).ToFunc()
			}
			// ByDefaultSubtitleStreamIndex orders the results by the default_subtitle_stream_index field.
			func ByDefaultSubtitleStreamIndex(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldDefaultSubtitleStreamIndex, opts...).ToFunc()
			}
			// ByItemField orders the results by item field.
			func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
				return func(s *sql.Selector) {
					sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
				}
			}
			// ByStreamsCount orders the results by streams count.
			func ByStreamsCount(opts ...sql.OrderTermOption) OrderOption {
				return func(s *sql.Selector) {
					sqlgraph.OrderByNeighborsCount(s, newStreamsStep(), opts...)
				}
			}

			// ByStreams orders the results by streams terms.
			func ByStreams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
				return func(s *sql.Selector) {
					sqlgraph.OrderByNeighborTerms(s, newStreamsStep(), append([]sql.OrderTerm{term}, terms...)...)
				}
			}
			// ByAttachmentsCount orders the results by attachments count.
			func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
				return func(s *sql.Selector) {
					sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
				}
			}

			// ByAttachments orders the results by attachments terms.
			func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
				return func(s *sql.Selector) {
					sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
				}
			}
		func newItemStep() *sqlgraph.Step {
			return sqlgraph.NewStep(
					sqlgraph.From(Table, FieldID),
						sqlgraph.To(ItemInverseTable, FieldID),
				sqlgraph.Edge(sqlgraph.M2O, true, ItemTable,ItemColumn),
			)
		}
		func newStreamsStep() *sqlgraph.Step {
			return sqlgraph.NewStep(
					sqlgraph.From(Table, FieldID),
						sqlgraph.To(StreamsInverseTable, FieldID),
				sqlgraph.Edge(sqlgraph.O2M, false, StreamsTable,StreamsColumn),
			)
		}
		func newAttachmentsStep() *sqlgraph.Step {
			return sqlgraph.NewStep(
					sqlgraph.From(Table, FieldID),
						sqlgraph.To(AttachmentsInverseTable, FieldID),
				sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable,AttachmentsColumn),
			)
		}







