
// Code generated by ent, DO NOT EDIT.



	

package playlistshare




import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/FreekingDean/gojellyfin/internal/store/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)



	// ID filters vertices based on their ID field.
	func ID(id uuid.UUID) predicate.PlaylistShare {
			return predicate.PlaylistShare(sql.FieldEQ(FieldID, id))
	}

	
		
		
		
		// IDEQ applies the EQ predicate on the ID field.
		func IDEQ(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldID, id))
		}
	
		
		
		
		// IDNEQ applies the NEQ predicate on the ID field.
		func IDNEQ(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNEQ(FieldID, id))
		}
	
		
		
		
		// IDIn applies the In predicate on the ID field.
		func IDIn(ids ...uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldIn(FieldID, ids...))
		}
	
		
		
		
		// IDNotIn applies the NotIn predicate on the ID field.
		func IDNotIn(ids ...uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNotIn(FieldID, ids...))
		}
	
		
		
		
		// IDGT applies the GT predicate on the ID field.
		func IDGT(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGT(FieldID, id))
		}
	
		
		
		
		// IDGTE applies the GTE predicate on the ID field.
		func IDGTE(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGTE(FieldID, id))
		}
	
		
		
		
		// IDLT applies the LT predicate on the ID field.
		func IDLT(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLT(FieldID, id))
		}
	
		
		
		
		// IDLTE applies the LTE predicate on the ID field.
		func IDLTE(id uuid.UUID) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLTE(FieldID, id))
		}
	



	
	
	
	
	
		
		// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
		func CreatedAt(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldCreatedAt, v))
		}

	
	
	
	
	
		
		// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
		func UpdatedAt(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldUpdatedAt, v))
		}

	
	
	
	
	
		
		// CanEdit applies equality check predicate on the "can_edit" field. It's identical to CanEditEQ.
		func CanEdit(v bool) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldCanEdit, v))
		}



	
		
		
		
		
		// CreatedAtEQ applies the EQ predicate on the "created_at" field.
		func CreatedAtEQ(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldCreatedAt, v))
		}
	
		
		
		
		
		// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
		func CreatedAtNEQ(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNEQ(FieldCreatedAt, v))
		}
	
		
		
		
		
		// CreatedAtIn applies the In predicate on the "created_at" field.
		func CreatedAtIn(vs ...time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldIn(FieldCreatedAt, vs...))
		}
	
		
		
		
		
		// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
		func CreatedAtNotIn(vs ...time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNotIn(FieldCreatedAt, vs...))
		}
	
		
		
		
		
		// CreatedAtGT applies the GT predicate on the "created_at" field.
		func CreatedAtGT(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGT(FieldCreatedAt, v))
		}
	
		
		
		
		
		// CreatedAtGTE applies the GTE predicate on the "created_at" field.
		func CreatedAtGTE(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGTE(FieldCreatedAt, v))
		}
	
		
		
		
		
		// CreatedAtLT applies the LT predicate on the "created_at" field.
		func CreatedAtLT(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLT(FieldCreatedAt, v))
		}
	
		
		
		
		
		// CreatedAtLTE applies the LTE predicate on the "created_at" field.
		func CreatedAtLTE(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLTE(FieldCreatedAt, v))
		}
	

	
		
		
		
		
		// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
		func UpdatedAtEQ(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldUpdatedAt, v))
		}
	
		
		
		
		
		// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
		func UpdatedAtNEQ(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNEQ(FieldUpdatedAt, v))
		}
	
		
		
		
		
		// UpdatedAtIn applies the In predicate on the "updated_at" field.
		func UpdatedAtIn(vs ...time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldIn(FieldUpdatedAt, vs...))
		}
	
		
		
		
		
		// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
		func UpdatedAtNotIn(vs ...time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNotIn(FieldUpdatedAt, vs...))
		}
	
		
		
		
		
		// UpdatedAtGT applies the GT predicate on the "updated_at" field.
		func UpdatedAtGT(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGT(FieldUpdatedAt, v))
		}
	
		
		
		
		
		// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
		func UpdatedAtGTE(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldGTE(FieldUpdatedAt, v))
		}
	
		
		
		
		
		// UpdatedAtLT applies the LT predicate on the "updated_at" field.
		func UpdatedAtLT(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLT(FieldUpdatedAt, v))
		}
	
		
		
		
		
		// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
		func UpdatedAtLTE(v time.Time) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldLTE(FieldUpdatedAt, v))
		}
	

	
		
		
		
		
		// CanEditEQ applies the EQ predicate on the "can_edit" field.
		func CanEditEQ(v bool) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldEQ(FieldCanEdit, v))
		}
	
		
		
		
		
		// CanEditNEQ applies the NEQ predicate on the "can_edit" field.
		func CanEditNEQ(v bool) predicate.PlaylistShare {
				return predicate.PlaylistShare(sql.FieldNEQ(FieldCanEdit, v))
		}
	



	
	// HasPlaylist applies the HasEdge predicate on the "playlist" edge.
	func HasPlaylist() predicate.PlaylistShare {
		return predicate.PlaylistShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
				sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlaylistTable,PlaylistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
	}
	
	// HasPlaylistWith applies the HasEdge predicate on the "playlist" edge with a given conditions (other predicates).
	func HasPlaylistWith(preds ...predicate.Playlist) predicate.PlaylistShare {
		return predicate.PlaylistShare(func(s *sql.Selector) {
		step := newPlaylistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
	}

	
	// HasUser applies the HasEdge predicate on the "user" edge.
	func HasUser() predicate.PlaylistShare {
		return predicate.PlaylistShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
				sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable,UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
	}
	
	// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
	func HasUserWith(preds ...predicate.User) predicate.PlaylistShare {
		return predicate.PlaylistShare(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
	}


// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlaylistShare) predicate.PlaylistShare {
	return predicate.PlaylistShare(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlaylistShare) predicate.PlaylistShare {
	return predicate.PlaylistShare(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaylistShare) predicate.PlaylistShare {
	return predicate.PlaylistShare(sql.NotPredicates(p))
}





