apiVersion: v1
kind: Service
metadata:
  name: gojellyfin-transcode
  labels:
    app.kubernetes.io/name: gojellyfin
    app.kubernetes.io/component: transcode
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gojellyfin
    app.kubernetes.io/component: transcode
  ports:
    - name: http
      port: 80
      targetPort: http
