-- Modify "libraries" table
ALTER TABLE "libraries" ALTER COLUMN "collection_type" SET DEFAULT 'mixed';
-- Create index "libraries_name_key" to table: "libraries"
CREATE UNIQUE INDEX "libraries_name_key" ON "libraries" ("name");
-- Modify "library_options" table
ALTER TABLE "library_options" ALTER COLUMN "enabled" SET DEFAULT true, ALTER COLUMN "enable_photos" SET DEFAULT true, ALTER COLUMN "enable_realtime_monitor" SET DEFAULT true, ALTER COLUMN "enable_lufs_scan" SET DEFAULT true, ALTER COLUMN "enable_chapter_image_extraction" SET DEFAULT false, ALTER COLUMN "extract_chapter_images_during_library_scan" SET DEFAULT false, ALTER COLUMN "enable_trickplay_image_extraction" SET DEFAULT false, ALTER COLUMN "extract_trickplay_images_during_library_scan" SET DEFAULT false, ALTER COLUMN "save_local_metadata" SET DEFAULT false, ALTER COLUMN "enable_internet_providers" SET DEFAULT true, ALTER COLUMN "enable_automatic_series_grouping" SET DEFAULT false, ALTER COLUMN "enable_embedded_titles" SET DEFAULT false, ALTER COLUMN "enable_embedded_extras_titles" SET DEFAULT false, ALTER COLUMN "enable_embedded_episode_infos" SET DEFAULT false, ALTER COLUMN "skip_subtitles_if_embedded_subtitles_present" SET DEFAULT false, ALTER COLUMN "skip_subtitles_if_audio_track_matches" SET DEFAULT false, ALTER COLUMN "require_perfect_subtitle_match" SET DEFAULT true, ALTER COLUMN "save_subtitles_with_media" SET DEFAULT true, ALTER COLUMN "save_lyrics_with_media" SET DEFAULT false, ALTER COLUMN "save_trickplay_with_media" SET DEFAULT false, ALTER COLUMN "prefer_nonstandard_artists_tag" SET DEFAULT false, ALTER COLUMN "use_custom_tag_delimiters" SET DEFAULT false, ALTER COLUMN "automatically_add_to_collection" SET DEFAULT false, ALTER COLUMN "automatic_refresh_interval_days" SET DEFAULT 0, ALTER COLUMN "preferred_metadata_language" SET DEFAULT '', ALTER COLUMN "metadata_country_code" SET DEFAULT '', ALTER COLUMN "season_zero_display_name" SET DEFAULT 'Specials', ALTER COLUMN "allow_embedded_subtitles" SET DEFAULT 'AllowAll';
-- Modify "user_configurations" table
ALTER TABLE "user_configurations" ALTER COLUMN "play_default_audio_track" SET DEFAULT true, ALTER COLUMN "subtitle_mode" SET DEFAULT 'OnlyForced', ALTER COLUMN "display_missing_episodes" SET DEFAULT false, ALTER COLUMN "display_collections_view" SET DEFAULT false, ALTER COLUMN "enable_local_password" SET DEFAULT false, ALTER COLUMN "hide_played_in_latest" SET DEFAULT true, ALTER COLUMN "remember_audio_selections" SET DEFAULT true, ALTER COLUMN "enable_next_episode_auto_play" SET DEFAULT true, ALTER COLUMN "remember_subtitle_selections" SET DEFAULT true;
-- Create index "user_configurations_user_configuration_key" to table: "user_configurations"
CREATE UNIQUE INDEX "user_configurations_user_configuration_key" ON "user_configurations" ("user_configuration");
-- Modify "user_policies" table
ALTER TABLE "user_policies" ALTER COLUMN "is_administrator" SET DEFAULT false, ALTER COLUMN "is_hidden" SET DEFAULT false, ALTER COLUMN "is_disabled" SET DEFAULT false, ALTER COLUMN "enable_subtitle_management" SET DEFAULT true, ALTER COLUMN "enable_user_preference_access" SET DEFAULT true, ALTER COLUMN "enable_remote_control_of_other_users" SET DEFAULT false, ALTER COLUMN "enable_shared_device_control" SET DEFAULT true, ALTER COLUMN "enable_remote_access" SET DEFAULT true, ALTER COLUMN "enable_live_tv_management" SET DEFAULT false, ALTER COLUMN "enable_live_tv_access" SET DEFAULT false, ALTER COLUMN "enable_media_playback" SET DEFAULT true, ALTER COLUMN "enable_audio_playback_transcoding" SET DEFAULT true, ALTER COLUMN "enable_video_playback_transcoding" SET DEFAULT true, ALTER COLUMN "enable_playback_remuxing" SET DEFAULT true, ALTER COLUMN "force_remote_source_transcoding" SET DEFAULT false, ALTER COLUMN "enable_content_deletion" SET DEFAULT false, ALTER COLUMN "enable_content_downloading" SET DEFAULT true, ALTER COLUMN "enable_sync_transcoding" SET DEFAULT true, ALTER COLUMN "enable_media_conversion" SET DEFAULT true, ALTER COLUMN "enable_public_sharing" SET DEFAULT true, ALTER COLUMN "enable_all_devices" SET DEFAULT true, ALTER COLUMN "enable_all_channels" SET DEFAULT true, ALTER COLUMN "enable_all_folders" SET DEFAULT true, ALTER COLUMN "invalid_login_attempt_count" SET DEFAULT 0, ALTER COLUMN "login_attempts_before_lockout" SET DEFAULT -1, ALTER COLUMN "max_active_sessions" SET DEFAULT 0, ALTER COLUMN "remote_client_bitrate_limit" SET DEFAULT 0, ALTER COLUMN "authentication_provider_id" SET DEFAULT 'Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider', ALTER COLUMN "password_reset_provider_id" SET DEFAULT 'Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider', ALTER COLUMN "sync_play_access" SET DEFAULT 'CreateAndJoinGroups';
-- Create index "user_policies_user_policy_key" to table: "user_policies"
CREATE UNIQUE INDEX "user_policies_user_policy_key" ON "user_policies" ("user_policy");
-- Drop index "item_path" from table: "items"
DROP INDEX "item_path";
-- Modify "items" table
ALTER TABLE "items" DROP CONSTRAINT "items_items_children", DROP CONSTRAINT "items_libraries_items", ALTER COLUMN "media_type" SET DEFAULT 'Unknown', ALTER COLUMN "location_type" SET DEFAULT 'FileSystem', ALTER COLUMN "forced_sort_name" SET DEFAULT false, ALTER COLUMN "is_folder" SET DEFAULT false, ALTER COLUMN "is_placeholder" SET DEFAULT false, ALTER COLUMN "lock_data" SET DEFAULT false, ALTER COLUMN "has_lyrics" SET DEFAULT false, ALTER COLUMN "has_subtitles" SET DEFAULT false, ALTER COLUMN "enable_media_source_display" SET DEFAULT true, DROP COLUMN "item_children", DROP COLUMN "library_items", ADD COLUMN "date_modified" timestamptz NULL, ADD COLUMN "probed_at" timestamptz NULL, ADD COLUMN "parent_id" uuid NULL, ADD COLUMN "library_id" uuid NULL, ADD CONSTRAINT "items_items_children" FOREIGN KEY ("parent_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "items_libraries_items" FOREIGN KEY ("library_id") REFERENCES "libraries" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "item_library_id_path" to table: "items"
CREATE UNIQUE INDEX "item_library_id_path" ON "items" ("library_id", "path");
-- Modify "images" table
ALTER TABLE "images" DROP CONSTRAINT "images_items_images", ALTER COLUMN "index" SET DEFAULT 0, DROP COLUMN "item_images", ADD COLUMN "tag" character varying NOT NULL, ADD COLUMN "item_id" uuid NOT NULL, ADD CONSTRAINT "images_items_images" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Create index "image_item_id_kind_index" to table: "images"
CREATE UNIQUE INDEX "image_item_id_kind_index" ON "images" ("item_id", "kind", "index");
-- Modify "media_sources" table
ALTER TABLE "media_sources" DROP CONSTRAINT "media_sources_items_media_sources", ALTER COLUMN "protocol" SET DEFAULT 'File', ALTER COLUMN "kind" SET DEFAULT 'Default', ALTER COLUMN "is_remote" SET DEFAULT false, ALTER COLUMN "is_infinite_stream" SET DEFAULT false, ALTER COLUMN "supports_transcoding" SET DEFAULT true, ALTER COLUMN "supports_direct_stream" SET DEFAULT true, ALTER COLUMN "supports_direct_play" SET DEFAULT true, ALTER COLUMN "supports_probing" SET DEFAULT true, ALTER COLUMN "read_at_native_framerate" SET DEFAULT false, ALTER COLUMN "ignore_dts" SET DEFAULT false, ALTER COLUMN "ignore_index" SET DEFAULT false, ALTER COLUMN "gen_pts_input" SET DEFAULT false, ALTER COLUMN "requires_looping" SET DEFAULT false, ALTER COLUMN "has_segments" SET DEFAULT false, DROP COLUMN "item_media_sources", ADD COLUMN "item_id" uuid NOT NULL, ADD CONSTRAINT "media_sources_items_media_sources" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "media_streams" table
ALTER TABLE "media_streams" DROP CONSTRAINT "media_streams_media_sources_streams", ALTER COLUMN "index" SET DEFAULT 0, ALTER COLUMN "is_default" SET DEFAULT false, ALTER COLUMN "is_forced" SET DEFAULT false, ALTER COLUMN "is_external" SET DEFAULT false, ALTER COLUMN "is_interlaced" SET DEFAULT false, ALTER COLUMN "is_anamorphic" SET DEFAULT false, ALTER COLUMN "is_avc" SET DEFAULT false, ALTER COLUMN "is_hearing_impaired" SET DEFAULT false, DROP COLUMN "media_source_streams", ADD COLUMN "source_id" uuid NOT NULL, ADD CONSTRAINT "media_streams_media_sources_streams" FOREIGN KEY ("source_id") REFERENCES "media_sources" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Create index "mediastream_source_id_index" to table: "media_streams"
CREATE UNIQUE INDEX "mediastream_source_id_index" ON "media_streams" ("source_id", "index");
-- Modify "users" table
ALTER TABLE "users" ADD COLUMN "last_login_at" timestamptz NULL, ADD COLUMN "last_activity_at" timestamptz NULL;
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Modify "user_item_data" table
ALTER TABLE "user_item_data" DROP CONSTRAINT "user_item_data_items_user_data", DROP CONSTRAINT "user_item_data_users_item_data", ALTER COLUMN "played" SET DEFAULT false, ALTER COLUMN "is_favorite" SET DEFAULT false, ALTER COLUMN "play_count" SET DEFAULT 0, ALTER COLUMN "playback_position_ticks" SET DEFAULT 0, DROP COLUMN "item_user_data", DROP COLUMN "user_item_data", ADD COLUMN "item_id" uuid NOT NULL, ADD COLUMN "user_id" uuid NOT NULL, ADD CONSTRAINT "user_item_data_items_user_data" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "user_item_data_users_item_data" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Create index "useritemdata_user_id_item_id" to table: "user_item_data"
CREATE UNIQUE INDEX "useritemdata_user_id_item_id" ON "user_item_data" ("user_id", "item_id");
