// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/item"
	"github.com/FreekingDean/gojellyfin/internal/store/itemsource"
	"github.com/FreekingDean/gojellyfin/internal/store/mediastream"
	"github.com/FreekingDean/gojellyfin/internal/store/source"
	"github.com/google/uuid"
)

// ItemSourceCreate is the builder for creating a ItemSource entity.
type ItemSourceCreate struct {
	config
	mutation *ItemSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemSourceCreate) SetCreatedAt(v time.Time) *ItemSourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableCreatedAt(v *time.Time) *ItemSourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemSourceCreate) SetUpdatedAt(v time.Time) *ItemSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableUpdatedAt(v *time.Time) *ItemSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *ItemSourceCreate) SetItemID(v uuid.UUID) *ItemSourceCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ItemSourceCreate) SetSourceID(v uuid.UUID) *ItemSourceCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ItemSourceCreate) SetName(v string) *ItemSourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ItemSourceCreate) SetPath(v string) *ItemSourceCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetContainer sets the "container" field.
func (_c *ItemSourceCreate) SetContainer(v string) *ItemSourceCreate {
	_c.mutation.SetContainer(v)
	return _c
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableContainer(v *string) *ItemSourceCreate {
	if v != nil {
		_c.SetContainer(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *ItemSourceCreate) SetSize(v int64) *ItemSourceCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableSize(v *int64) *ItemSourceCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_c *ItemSourceCreate) SetRunTimeTicks(v int64) *ItemSourceCreate {
	_c.mutation.SetRunTimeTicks(v)
	return _c
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableRunTimeTicks(v *int64) *ItemSourceCreate {
	if v != nil {
		_c.SetRunTimeTicks(*v)
	}
	return _c
}

// SetBitrate sets the "bitrate" field.
func (_c *ItemSourceCreate) SetBitrate(v int32) *ItemSourceCreate {
	_c.mutation.SetBitrate(v)
	return _c
}

// SetNillableBitrate sets the "bitrate" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableBitrate(v *int32) *ItemSourceCreate {
	if v != nil {
		_c.SetBitrate(*v)
	}
	return _c
}

// SetDateModified sets the "date_modified" field.
func (_c *ItemSourceCreate) SetDateModified(v time.Time) *ItemSourceCreate {
	_c.mutation.SetDateModified(v)
	return _c
}

// SetNillableDateModified sets the "date_modified" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableDateModified(v *time.Time) *ItemSourceCreate {
	if v != nil {
		_c.SetDateModified(*v)
	}
	return _c
}

// SetProbedAt sets the "probed_at" field.
func (_c *ItemSourceCreate) SetProbedAt(v time.Time) *ItemSourceCreate {
	_c.mutation.SetProbedAt(v)
	return _c
}

// SetNillableProbedAt sets the "probed_at" field if the given value is not nil.
func (_c *ItemSourceCreate) SetNillableProbedAt(v *time.Time) *ItemSourceCreate {
	if v != nil {
		_c.SetProbedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemSourceCreate) SetID(v uuid.UUID) *ItemSourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *ItemSourceCreate) SetItem(v *Item) *ItemSourceCreate {
	return _c.SetItemID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_c *ItemSourceCreate) SetSource(v *Source) *ItemSourceCreate {
	return _c.SetSourceID(v.ID)
}

// AddStreamIDs adds the "streams" edge to the MediaStream entity by IDs.
func (_c *ItemSourceCreate) AddStreamIDs(ids ...uuid.UUID) *ItemSourceCreate {
	_c.mutation.AddStreamIDs(ids...)
	return _c
}

// AddStreams adds the "streams" edges to the MediaStream entity.
func (_c *ItemSourceCreate) AddStreams(v ...*MediaStream) *ItemSourceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStreamIDs(ids...)
}

// Mutation returns the ItemSourceMutation object of the builder.
func (_c *ItemSourceCreate) Mutation() *ItemSourceMutation {
	return _c.mutation
}

// Save creates the ItemSource in the database.
func (_c *ItemSourceCreate) Save(ctx context.Context) (*ItemSource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemSourceCreate) SaveX(ctx context.Context) *ItemSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemSourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itemsource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itemsource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemSourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`store: missing required field "ItemSource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`store: missing required field "ItemSource.updated_at"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`store: missing required field "ItemSource.item_id"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`store: missing required field "ItemSource.source_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`store: missing required field "ItemSource.name"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`store: missing required field "ItemSource.path"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`store: missing required edge "ItemSource.item"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`store: missing required edge "ItemSource.source"`)}
	}
	return nil
}

func (_c *ItemSourceCreate) sqlSave(ctx context.Context) (*ItemSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemSourceCreate) createSpec() (*ItemSource, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itemsource.Table, sqlgraph.NewFieldSpec(itemsource.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itemsource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itemsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(itemsource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(itemsource.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Container(); ok {
		_spec.SetField(itemsource.FieldContainer, field.TypeString, value)
		_node.Container = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(itemsource.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.RunTimeTicks(); ok {
		_spec.SetField(itemsource.FieldRunTimeTicks, field.TypeInt64, value)
		_node.RunTimeTicks = value
	}
	if value, ok := _c.mutation.Bitrate(); ok {
		_spec.SetField(itemsource.FieldBitrate, field.TypeInt32, value)
		_node.Bitrate = value
	}
	if value, ok := _c.mutation.DateModified(); ok {
		_spec.SetField(itemsource.FieldDateModified, field.TypeTime, value)
		_node.DateModified = value
	}
	if value, ok := _c.mutation.ProbedAt(); ok {
		_spec.SetField(itemsource.FieldProbedAt, field.TypeTime, value)
		_node.ProbedAt = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemsource.ItemTable,
			Columns: []string{itemsource.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemsource.SourceTable,
			Columns: []string{itemsource.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StreamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.StreamsTable,
			Columns: []string{itemsource.StreamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediastream.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemSource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemSourceCreate) OnConflict(opts ...sql.ConflictOption) *ItemSourceUpsertOne {
	_c.conflict = opts
	return &ItemSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemSourceCreate) OnConflictColumns(columns ...string) *ItemSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemSourceUpsertOne{
		create: _c,
	}
}

type (
	// ItemSourceUpsertOne is the builder for "upsert"-ing
	//  one ItemSource node.
	ItemSourceUpsertOne struct {
		create *ItemSourceCreate
	}

	// ItemSourceUpsert is the "OnConflict" setter.
	ItemSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *ItemSourceUpsert) SetCreatedAt(v time.Time) *ItemSourceUpsert {
	u.Set(itemsource.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateCreatedAt() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemSourceUpsert) SetUpdatedAt(v time.Time) *ItemSourceUpsert {
	u.Set(itemsource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateUpdatedAt() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldUpdatedAt)
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemSourceUpsert) SetItemID(v uuid.UUID) *ItemSourceUpsert {
	u.Set(itemsource.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateItemID() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldItemID)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *ItemSourceUpsert) SetSourceID(v uuid.UUID) *ItemSourceUpsert {
	u.Set(itemsource.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateSourceID() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldSourceID)
	return u
}

// SetName sets the "name" field.
func (u *ItemSourceUpsert) SetName(v string) *ItemSourceUpsert {
	u.Set(itemsource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateName() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldName)
	return u
}

// SetPath sets the "path" field.
func (u *ItemSourceUpsert) SetPath(v string) *ItemSourceUpsert {
	u.Set(itemsource.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdatePath() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldPath)
	return u
}

// SetContainer sets the "container" field.
func (u *ItemSourceUpsert) SetContainer(v string) *ItemSourceUpsert {
	u.Set(itemsource.FieldContainer, v)
	return u
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateContainer() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldContainer)
	return u
}

// ClearContainer clears the value of the "container" field.
func (u *ItemSourceUpsert) ClearContainer() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldContainer)
	return u
}

// SetSize sets the "size" field.
func (u *ItemSourceUpsert) SetSize(v int64) *ItemSourceUpsert {
	u.Set(itemsource.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateSize() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *ItemSourceUpsert) AddSize(v int64) *ItemSourceUpsert {
	u.Add(itemsource.FieldSize, v)
	return u
}

// ClearSize clears the value of the "size" field.
func (u *ItemSourceUpsert) ClearSize() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldSize)
	return u
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (u *ItemSourceUpsert) SetRunTimeTicks(v int64) *ItemSourceUpsert {
	u.Set(itemsource.FieldRunTimeTicks, v)
	return u
}

// UpdateRunTimeTicks sets the "run_time_ticks" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateRunTimeTicks() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldRunTimeTicks)
	return u
}

// AddRunTimeTicks adds v to the "run_time_ticks" field.
func (u *ItemSourceUpsert) AddRunTimeTicks(v int64) *ItemSourceUpsert {
	u.Add(itemsource.FieldRunTimeTicks, v)
	return u
}

// ClearRunTimeTicks clears the value of the "run_time_ticks" field.
func (u *ItemSourceUpsert) ClearRunTimeTicks() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldRunTimeTicks)
	return u
}

// SetBitrate sets the "bitrate" field.
func (u *ItemSourceUpsert) SetBitrate(v int32) *ItemSourceUpsert {
	u.Set(itemsource.FieldBitrate, v)
	return u
}

// UpdateBitrate sets the "bitrate" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateBitrate() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldBitrate)
	return u
}

// AddBitrate adds v to the "bitrate" field.
func (u *ItemSourceUpsert) AddBitrate(v int32) *ItemSourceUpsert {
	u.Add(itemsource.FieldBitrate, v)
	return u
}

// ClearBitrate clears the value of the "bitrate" field.
func (u *ItemSourceUpsert) ClearBitrate() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldBitrate)
	return u
}

// SetDateModified sets the "date_modified" field.
func (u *ItemSourceUpsert) SetDateModified(v time.Time) *ItemSourceUpsert {
	u.Set(itemsource.FieldDateModified, v)
	return u
}

// UpdateDateModified sets the "date_modified" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateDateModified() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldDateModified)
	return u
}

// ClearDateModified clears the value of the "date_modified" field.
func (u *ItemSourceUpsert) ClearDateModified() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldDateModified)
	return u
}

// SetProbedAt sets the "probed_at" field.
func (u *ItemSourceUpsert) SetProbedAt(v time.Time) *ItemSourceUpsert {
	u.Set(itemsource.FieldProbedAt, v)
	return u
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ItemSourceUpsert) UpdateProbedAt() *ItemSourceUpsert {
	u.SetExcluded(itemsource.FieldProbedAt)
	return u
}

// ClearProbedAt clears the value of the "probed_at" field.
func (u *ItemSourceUpsert) ClearProbedAt() *ItemSourceUpsert {
	u.SetNull(itemsource.FieldProbedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemsource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemSourceUpsertOne) UpdateNewValues() *ItemSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(itemsource.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemSourceUpsertOne) Ignore() *ItemSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemSourceUpsertOne) DoNothing() *ItemSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemSourceCreate.OnConflict
// documentation for more info.
func (u *ItemSourceUpsertOne) Update(set func(*ItemSourceUpsert)) *ItemSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ItemSourceUpsertOne) SetCreatedAt(v time.Time) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateCreatedAt() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemSourceUpsertOne) SetUpdatedAt(v time.Time) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateUpdatedAt() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetItemID sets the "item_id" field.
func (u *ItemSourceUpsertOne) SetItemID(v uuid.UUID) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateItemID() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateItemID()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ItemSourceUpsertOne) SetSourceID(v uuid.UUID) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateSourceID() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateSourceID()
	})
}

// SetName sets the "name" field.
func (u *ItemSourceUpsertOne) SetName(v string) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateName() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateName()
	})
}

// SetPath sets the "path" field.
func (u *ItemSourceUpsertOne) SetPath(v string) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdatePath() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdatePath()
	})
}

// SetContainer sets the "container" field.
func (u *ItemSourceUpsertOne) SetContainer(v string) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetContainer(v)
	})
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateContainer() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateContainer()
	})
}

// ClearContainer clears the value of the "container" field.
func (u *ItemSourceUpsertOne) ClearContainer() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearContainer()
	})
}

// SetSize sets the "size" field.
func (u *ItemSourceUpsertOne) SetSize(v int64) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ItemSourceUpsertOne) AddSize(v int64) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateSize() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateSize()
	})
}

// ClearSize clears the value of the "size" field.
func (u *ItemSourceUpsertOne) ClearSize() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearSize()
	})
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (u *ItemSourceUpsertOne) SetRunTimeTicks(v int64) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetRunTimeTicks(v)
	})
}

// AddRunTimeTicks adds v to the "run_time_ticks" field.
func (u *ItemSourceUpsertOne) AddRunTimeTicks(v int64) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddRunTimeTicks(v)
	})
}

// UpdateRunTimeTicks sets the "run_time_ticks" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateRunTimeTicks() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateRunTimeTicks()
	})
}

// ClearRunTimeTicks clears the value of the "run_time_ticks" field.
func (u *ItemSourceUpsertOne) ClearRunTimeTicks() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearRunTimeTicks()
	})
}

// SetBitrate sets the "bitrate" field.
func (u *ItemSourceUpsertOne) SetBitrate(v int32) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetBitrate(v)
	})
}

// AddBitrate adds v to the "bitrate" field.
func (u *ItemSourceUpsertOne) AddBitrate(v int32) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddBitrate(v)
	})
}

// UpdateBitrate sets the "bitrate" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateBitrate() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateBitrate()
	})
}

// ClearBitrate clears the value of the "bitrate" field.
func (u *ItemSourceUpsertOne) ClearBitrate() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearBitrate()
	})
}

// SetDateModified sets the "date_modified" field.
func (u *ItemSourceUpsertOne) SetDateModified(v time.Time) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetDateModified(v)
	})
}

// UpdateDateModified sets the "date_modified" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateDateModified() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateDateModified()
	})
}

// ClearDateModified clears the value of the "date_modified" field.
func (u *ItemSourceUpsertOne) ClearDateModified() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearDateModified()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ItemSourceUpsertOne) SetProbedAt(v time.Time) *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ItemSourceUpsertOne) UpdateProbedAt() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateProbedAt()
	})
}

// ClearProbedAt clears the value of the "probed_at" field.
func (u *ItemSourceUpsertOne) ClearProbedAt() *ItemSourceUpsertOne {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearProbedAt()
	})
}

// Exec executes the query.
func (u *ItemSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for ItemSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemSourceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("store: ItemSourceUpsertOne.ID is not supported by MySQL driver. Use ItemSourceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemSourceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemSourceCreateBulk is the builder for creating many ItemSource entities in bulk.
type ItemSourceCreateBulk struct {
	config
	err      error
	builders []*ItemSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the ItemSource entities in the database.
func (_c *ItemSourceCreateBulk) Save(ctx context.Context) ([]*ItemSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemSourceCreateBulk) SaveX(ctx context.Context) []*ItemSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemSourceUpsertBulk {
	_c.conflict = opts
	return &ItemSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemSourceCreateBulk) OnConflictColumns(columns ...string) *ItemSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemSourceUpsertBulk{
		create: _c,
	}
}

// ItemSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of ItemSource nodes.
type ItemSourceUpsertBulk struct {
	create *ItemSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemsource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemSourceUpsertBulk) UpdateNewValues() *ItemSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(itemsource.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemSourceUpsertBulk) Ignore() *ItemSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemSourceUpsertBulk) DoNothing() *ItemSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemSourceCreateBulk.OnConflict
// documentation for more info.
func (u *ItemSourceUpsertBulk) Update(set func(*ItemSourceUpsert)) *ItemSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ItemSourceUpsertBulk) SetCreatedAt(v time.Time) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateCreatedAt() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemSourceUpsertBulk) SetUpdatedAt(v time.Time) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateUpdatedAt() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetItemID sets the "item_id" field.
func (u *ItemSourceUpsertBulk) SetItemID(v uuid.UUID) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateItemID() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateItemID()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ItemSourceUpsertBulk) SetSourceID(v uuid.UUID) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateSourceID() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateSourceID()
	})
}

// SetName sets the "name" field.
func (u *ItemSourceUpsertBulk) SetName(v string) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateName() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateName()
	})
}

// SetPath sets the "path" field.
func (u *ItemSourceUpsertBulk) SetPath(v string) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdatePath() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdatePath()
	})
}

// SetContainer sets the "container" field.
func (u *ItemSourceUpsertBulk) SetContainer(v string) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetContainer(v)
	})
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateContainer() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateContainer()
	})
}

// ClearContainer clears the value of the "container" field.
func (u *ItemSourceUpsertBulk) ClearContainer() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearContainer()
	})
}

// SetSize sets the "size" field.
func (u *ItemSourceUpsertBulk) SetSize(v int64) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ItemSourceUpsertBulk) AddSize(v int64) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateSize() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateSize()
	})
}

// ClearSize clears the value of the "size" field.
func (u *ItemSourceUpsertBulk) ClearSize() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearSize()
	})
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (u *ItemSourceUpsertBulk) SetRunTimeTicks(v int64) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetRunTimeTicks(v)
	})
}

// AddRunTimeTicks adds v to the "run_time_ticks" field.
func (u *ItemSourceUpsertBulk) AddRunTimeTicks(v int64) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddRunTimeTicks(v)
	})
}

// UpdateRunTimeTicks sets the "run_time_ticks" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateRunTimeTicks() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateRunTimeTicks()
	})
}

// ClearRunTimeTicks clears the value of the "run_time_ticks" field.
func (u *ItemSourceUpsertBulk) ClearRunTimeTicks() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearRunTimeTicks()
	})
}

// SetBitrate sets the "bitrate" field.
func (u *ItemSourceUpsertBulk) SetBitrate(v int32) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetBitrate(v)
	})
}

// AddBitrate adds v to the "bitrate" field.
func (u *ItemSourceUpsertBulk) AddBitrate(v int32) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.AddBitrate(v)
	})
}

// UpdateBitrate sets the "bitrate" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateBitrate() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateBitrate()
	})
}

// ClearBitrate clears the value of the "bitrate" field.
func (u *ItemSourceUpsertBulk) ClearBitrate() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearBitrate()
	})
}

// SetDateModified sets the "date_modified" field.
func (u *ItemSourceUpsertBulk) SetDateModified(v time.Time) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetDateModified(v)
	})
}

// UpdateDateModified sets the "date_modified" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateDateModified() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateDateModified()
	})
}

// ClearDateModified clears the value of the "date_modified" field.
func (u *ItemSourceUpsertBulk) ClearDateModified() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearDateModified()
	})
}

// SetProbedAt sets the "probed_at" field.
func (u *ItemSourceUpsertBulk) SetProbedAt(v time.Time) *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.SetProbedAt(v)
	})
}

// UpdateProbedAt sets the "probed_at" field to the value that was provided on create.
func (u *ItemSourceUpsertBulk) UpdateProbedAt() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.UpdateProbedAt()
	})
}

// ClearProbedAt clears the value of the "probed_at" field.
func (u *ItemSourceUpsertBulk) ClearProbedAt() *ItemSourceUpsertBulk {
	return u.Update(func(s *ItemSourceUpsert) {
		s.ClearProbedAt()
	})
}

// Exec executes the query.
func (u *ItemSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("store: OnConflict was set for builder %d. Set it on the ItemSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for ItemSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
