// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/item"
	"github.com/FreekingDean/gojellyfin/internal/store/library"
	"github.com/FreekingDean/gojellyfin/internal/store/libraryoptions"
	"github.com/FreekingDean/gojellyfin/internal/store/predicate"
	"github.com/google/uuid"
)

// LibraryUpdate is the builder for updating Library entities.
type LibraryUpdate struct {
	config
	hooks    []Hook
	mutation *LibraryMutation
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdate) Where(ps ...predicate.Library) *LibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LibraryUpdate) SetCreatedAt(v time.Time) *LibraryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableCreatedAt(v *time.Time) *LibraryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdate) SetUpdatedAt(v time.Time) *LibraryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *LibraryUpdate) SetName(v string) *LibraryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableName(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCollectionType sets the "collection_type" field.
func (_u *LibraryUpdate) SetCollectionType(v library.CollectionType) *LibraryUpdate {
	_u.mutation.SetCollectionType(v)
	return _u
}

// SetNillableCollectionType sets the "collection_type" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableCollectionType(v *library.CollectionType) *LibraryUpdate {
	if v != nil {
		_u.SetCollectionType(*v)
	}
	return _u
}

// SetLocations sets the "locations" field.
func (_u *LibraryUpdate) SetLocations(v []string) *LibraryUpdate {
	_u.mutation.SetLocations(v)
	return _u
}

// AppendLocations appends value to the "locations" field.
func (_u *LibraryUpdate) AppendLocations(v []string) *LibraryUpdate {
	_u.mutation.AppendLocations(v)
	return _u
}

// SetOptionsID sets the "options" edge to the LibraryOptions entity by ID.
func (_u *LibraryUpdate) SetOptionsID(id uuid.UUID) *LibraryUpdate {
	_u.mutation.SetOptionsID(id)
	return _u
}

// SetNillableOptionsID sets the "options" edge to the LibraryOptions entity by ID if the given value is not nil.
func (_u *LibraryUpdate) SetNillableOptionsID(id *uuid.UUID) *LibraryUpdate {
	if id != nil {
		_u = _u.SetOptionsID(*id)
	}
	return _u
}

// SetOptions sets the "options" edge to the LibraryOptions entity.
func (_u *LibraryUpdate) SetOptions(v *LibraryOptions) *LibraryUpdate {
	return _u.SetOptionsID(v.ID)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *LibraryUpdate) AddItemIDs(ids ...uuid.UUID) *LibraryUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *LibraryUpdate) AddItems(v ...*Item) *LibraryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdate) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearOptions clears the "options" edge to the LibraryOptions entity.
func (_u *LibraryUpdate) ClearOptions() *LibraryUpdate {
	_u.mutation.ClearOptions()
	return _u
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *LibraryUpdate) ClearItems() *LibraryUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *LibraryUpdate) RemoveItemIDs(ids ...uuid.UUID) *LibraryUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *LibraryUpdate) RemoveItems(v ...*Item) *LibraryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LibraryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdate) check() error {
	if v, ok := _u.mutation.CollectionType(); ok {
		if err := library.CollectionTypeValidator(v); err != nil {
			return &ValidationError{Name: "collection_type", err: fmt.Errorf(`store: validator failed for field "Library.collection_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(library.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(library.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionType(); ok {
		_spec.SetField(library.FieldCollectionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Locations(); ok {
		_spec.SetField(library.FieldLocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, library.FieldLocations, value)
		})
	}
	if _u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   library.OptionsTable,
			Columns: []string{library.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(libraryoptions.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   library.OptionsTable,
			Columns: []string{library.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(libraryoptions.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LibraryUpdateOne is the builder for updating a single Library entity.
type LibraryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LibraryMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *LibraryUpdateOne) SetCreatedAt(v time.Time) *LibraryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableCreatedAt(v *time.Time) *LibraryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdateOne) SetUpdatedAt(v time.Time) *LibraryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *LibraryUpdateOne) SetName(v string) *LibraryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableName(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCollectionType sets the "collection_type" field.
func (_u *LibraryUpdateOne) SetCollectionType(v library.CollectionType) *LibraryUpdateOne {
	_u.mutation.SetCollectionType(v)
	return _u
}

// SetNillableCollectionType sets the "collection_type" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableCollectionType(v *library.CollectionType) *LibraryUpdateOne {
	if v != nil {
		_u.SetCollectionType(*v)
	}
	return _u
}

// SetLocations sets the "locations" field.
func (_u *LibraryUpdateOne) SetLocations(v []string) *LibraryUpdateOne {
	_u.mutation.SetLocations(v)
	return _u
}

// AppendLocations appends value to the "locations" field.
func (_u *LibraryUpdateOne) AppendLocations(v []string) *LibraryUpdateOne {
	_u.mutation.AppendLocations(v)
	return _u
}

// SetOptionsID sets the "options" edge to the LibraryOptions entity by ID.
func (_u *LibraryUpdateOne) SetOptionsID(id uuid.UUID) *LibraryUpdateOne {
	_u.mutation.SetOptionsID(id)
	return _u
}

// SetNillableOptionsID sets the "options" edge to the LibraryOptions entity by ID if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableOptionsID(id *uuid.UUID) *LibraryUpdateOne {
	if id != nil {
		_u = _u.SetOptionsID(*id)
	}
	return _u
}

// SetOptions sets the "options" edge to the LibraryOptions entity.
func (_u *LibraryUpdateOne) SetOptions(v *LibraryOptions) *LibraryUpdateOne {
	return _u.SetOptionsID(v.ID)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *LibraryUpdateOne) AddItemIDs(ids ...uuid.UUID) *LibraryUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *LibraryUpdateOne) AddItems(v ...*Item) *LibraryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdateOne) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearOptions clears the "options" edge to the LibraryOptions entity.
func (_u *LibraryUpdateOne) ClearOptions() *LibraryUpdateOne {
	_u.mutation.ClearOptions()
	return _u
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *LibraryUpdateOne) ClearItems() *LibraryUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *LibraryUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *LibraryUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *LibraryUpdateOne) RemoveItems(v ...*Item) *LibraryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdateOne) Where(ps ...predicate.Library) *LibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LibraryUpdateOne) Select(field string, fields ...string) *LibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Library entity.
func (_u *LibraryUpdateOne) Save(ctx context.Context) (*Library, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdateOne) SaveX(ctx context.Context) *Library {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdateOne) check() error {
	if v, ok := _u.mutation.CollectionType(); ok {
		if err := library.CollectionTypeValidator(v); err != nil {
			return &ValidationError{Name: "collection_type", err: fmt.Errorf(`store: validator failed for field "Library.collection_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LibraryUpdateOne) sqlSave(ctx context.Context) (_node *Library, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`store: missing "Library.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, library.FieldID)
		for _, f := range fields {
			if !library.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("store: invalid field %q for query", f)}
			}
			if f != library.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(library.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(library.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionType(); ok {
		_spec.SetField(library.FieldCollectionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Locations(); ok {
		_spec.SetField(library.FieldLocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, library.FieldLocations, value)
		})
	}
	if _u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   library.OptionsTable,
			Columns: []string{library.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(libraryoptions.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   library.OptionsTable,
			Columns: []string{library.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(libraryoptions.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Library{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
