// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/library"
	"github.com/FreekingDean/gojellyfin/internal/store/librarysource"
	"github.com/FreekingDean/gojellyfin/internal/store/predicate"
	"github.com/FreekingDean/gojellyfin/internal/store/source"
	"github.com/google/uuid"
)

// LibrarySourceUpdate is the builder for updating LibrarySource entities.
type LibrarySourceUpdate struct {
	config
	hooks    []Hook
	mutation *LibrarySourceMutation
}

// Where appends a list predicates to the LibrarySourceUpdate builder.
func (_u *LibrarySourceUpdate) Where(ps ...predicate.LibrarySource) *LibrarySourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LibrarySourceUpdate) SetCreatedAt(v time.Time) *LibrarySourceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LibrarySourceUpdate) SetNillableCreatedAt(v *time.Time) *LibrarySourceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibrarySourceUpdate) SetUpdatedAt(v time.Time) *LibrarySourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLibraryID sets the "library_id" field.
func (_u *LibrarySourceUpdate) SetLibraryID(v uuid.UUID) *LibrarySourceUpdate {
	_u.mutation.SetLibraryID(v)
	return _u
}

// SetNillableLibraryID sets the "library_id" field if the given value is not nil.
func (_u *LibrarySourceUpdate) SetNillableLibraryID(v *uuid.UUID) *LibrarySourceUpdate {
	if v != nil {
		_u.SetLibraryID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *LibrarySourceUpdate) SetSourceID(v uuid.UUID) *LibrarySourceUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *LibrarySourceUpdate) SetNillableSourceID(v *uuid.UUID) *LibrarySourceUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetTagFilter sets the "tag_filter" field.
func (_u *LibrarySourceUpdate) SetTagFilter(v string) *LibrarySourceUpdate {
	_u.mutation.SetTagFilter(v)
	return _u
}

// SetNillableTagFilter sets the "tag_filter" field if the given value is not nil.
func (_u *LibrarySourceUpdate) SetNillableTagFilter(v *string) *LibrarySourceUpdate {
	if v != nil {
		_u.SetTagFilter(*v)
	}
	return _u
}

// ClearTagFilter clears the value of the "tag_filter" field.
func (_u *LibrarySourceUpdate) ClearTagFilter() *LibrarySourceUpdate {
	_u.mutation.ClearTagFilter()
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *LibrarySourceUpdate) SetLibrary(v *Library) *LibrarySourceUpdate {
	return _u.SetLibraryID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *LibrarySourceUpdate) SetSource(v *Source) *LibrarySourceUpdate {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the LibrarySourceMutation object of the builder.
func (_u *LibrarySourceUpdate) Mutation() *LibrarySourceMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *LibrarySourceUpdate) ClearLibrary() *LibrarySourceUpdate {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *LibrarySourceUpdate) ClearSource() *LibrarySourceUpdate {
	_u.mutation.ClearSource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LibrarySourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibrarySourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LibrarySourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibrarySourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibrarySourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := librarysource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibrarySourceUpdate) check() error {
	if _u.mutation.LibraryCleared() && len(_u.mutation.LibraryIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "LibrarySource.library"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "LibrarySource.source"`)
	}
	return nil
}

func (_u *LibrarySourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(librarysource.Table, librarysource.Columns, sqlgraph.NewFieldSpec(librarysource.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(librarysource.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(librarysource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TagFilter(); ok {
		_spec.SetField(librarysource.FieldTagFilter, field.TypeString, value)
	}
	if _u.mutation.TagFilterCleared() {
		_spec.ClearField(librarysource.FieldTagFilter, field.TypeString)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.LibraryTable,
			Columns: []string{librarysource.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.LibraryTable,
			Columns: []string{librarysource.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.SourceTable,
			Columns: []string{librarysource.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.SourceTable,
			Columns: []string{librarysource.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{librarysource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LibrarySourceUpdateOne is the builder for updating a single LibrarySource entity.
type LibrarySourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LibrarySourceMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *LibrarySourceUpdateOne) SetCreatedAt(v time.Time) *LibrarySourceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LibrarySourceUpdateOne) SetNillableCreatedAt(v *time.Time) *LibrarySourceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibrarySourceUpdateOne) SetUpdatedAt(v time.Time) *LibrarySourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLibraryID sets the "library_id" field.
func (_u *LibrarySourceUpdateOne) SetLibraryID(v uuid.UUID) *LibrarySourceUpdateOne {
	_u.mutation.SetLibraryID(v)
	return _u
}

// SetNillableLibraryID sets the "library_id" field if the given value is not nil.
func (_u *LibrarySourceUpdateOne) SetNillableLibraryID(v *uuid.UUID) *LibrarySourceUpdateOne {
	if v != nil {
		_u.SetLibraryID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *LibrarySourceUpdateOne) SetSourceID(v uuid.UUID) *LibrarySourceUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *LibrarySourceUpdateOne) SetNillableSourceID(v *uuid.UUID) *LibrarySourceUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetTagFilter sets the "tag_filter" field.
func (_u *LibrarySourceUpdateOne) SetTagFilter(v string) *LibrarySourceUpdateOne {
	_u.mutation.SetTagFilter(v)
	return _u
}

// SetNillableTagFilter sets the "tag_filter" field if the given value is not nil.
func (_u *LibrarySourceUpdateOne) SetNillableTagFilter(v *string) *LibrarySourceUpdateOne {
	if v != nil {
		_u.SetTagFilter(*v)
	}
	return _u
}

// ClearTagFilter clears the value of the "tag_filter" field.
func (_u *LibrarySourceUpdateOne) ClearTagFilter() *LibrarySourceUpdateOne {
	_u.mutation.ClearTagFilter()
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *LibrarySourceUpdateOne) SetLibrary(v *Library) *LibrarySourceUpdateOne {
	return _u.SetLibraryID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *LibrarySourceUpdateOne) SetSource(v *Source) *LibrarySourceUpdateOne {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the LibrarySourceMutation object of the builder.
func (_u *LibrarySourceUpdateOne) Mutation() *LibrarySourceMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *LibrarySourceUpdateOne) ClearLibrary() *LibrarySourceUpdateOne {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *LibrarySourceUpdateOne) ClearSource() *LibrarySourceUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// Where appends a list predicates to the LibrarySourceUpdate builder.
func (_u *LibrarySourceUpdateOne) Where(ps ...predicate.LibrarySource) *LibrarySourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LibrarySourceUpdateOne) Select(field string, fields ...string) *LibrarySourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LibrarySource entity.
func (_u *LibrarySourceUpdateOne) Save(ctx context.Context) (*LibrarySource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibrarySourceUpdateOne) SaveX(ctx context.Context) *LibrarySource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LibrarySourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibrarySourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibrarySourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := librarysource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibrarySourceUpdateOne) check() error {
	if _u.mutation.LibraryCleared() && len(_u.mutation.LibraryIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "LibrarySource.library"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "LibrarySource.source"`)
	}
	return nil
}

func (_u *LibrarySourceUpdateOne) sqlSave(ctx context.Context) (_node *LibrarySource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(librarysource.Table, librarysource.Columns, sqlgraph.NewFieldSpec(librarysource.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`store: missing "LibrarySource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, librarysource.FieldID)
		for _, f := range fields {
			if !librarysource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("store: invalid field %q for query", f)}
			}
			if f != librarysource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(librarysource.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(librarysource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TagFilter(); ok {
		_spec.SetField(librarysource.FieldTagFilter, field.TypeString, value)
	}
	if _u.mutation.TagFilterCleared() {
		_spec.ClearField(librarysource.FieldTagFilter, field.TypeString)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.LibraryTable,
			Columns: []string{librarysource.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.LibraryTable,
			Columns: []string{librarysource.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.SourceTable,
			Columns: []string{librarysource.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   librarysource.SourceTable,
			Columns: []string{librarysource.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LibrarySource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{librarysource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
