// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/mediasource"
	"github.com/FreekingDean/gojellyfin/internal/store/mediastream"
	"github.com/google/uuid"
)

// MediaStreamCreate is the builder for creating a MediaStream entity.
type MediaStreamCreate struct {
	config
	mutation *MediaStreamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaStreamCreate) SetCreatedAt(v time.Time) *MediaStreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableCreatedAt(v *time.Time) *MediaStreamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaStreamCreate) SetUpdatedAt(v time.Time) *MediaStreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableUpdatedAt(v *time.Time) *MediaStreamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *MediaStreamCreate) SetSourceID(v uuid.UUID) *MediaStreamCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *MediaStreamCreate) SetKind(v mediastream.Kind) *MediaStreamCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetVideoRangeType sets the "video_range_type" field.
func (_c *MediaStreamCreate) SetVideoRangeType(v mediastream.VideoRangeType) *MediaStreamCreate {
	_c.mutation.SetVideoRangeType(v)
	return _c
}

// SetNillableVideoRangeType sets the "video_range_type" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableVideoRangeType(v *mediastream.VideoRangeType) *MediaStreamCreate {
	if v != nil {
		_c.SetVideoRangeType(*v)
	}
	return _c
}

// SetIndex sets the "index" field.
func (_c *MediaStreamCreate) SetIndex(v int32) *MediaStreamCreate {
	_c.mutation.SetIndex(v)
	return _c
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIndex(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetIndex(*v)
	}
	return _c
}

// SetCodec sets the "codec" field.
func (_c *MediaStreamCreate) SetCodec(v string) *MediaStreamCreate {
	_c.mutation.SetCodec(v)
	return _c
}

// SetNillableCodec sets the "codec" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableCodec(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetCodec(*v)
	}
	return _c
}

// SetProfile sets the "profile" field.
func (_c *MediaStreamCreate) SetProfile(v string) *MediaStreamCreate {
	_c.mutation.SetProfile(v)
	return _c
}

// SetNillableProfile sets the "profile" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableProfile(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetProfile(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *MediaStreamCreate) SetLanguage(v string) *MediaStreamCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableLanguage(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *MediaStreamCreate) SetTitle(v string) *MediaStreamCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableTitle(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *MediaStreamCreate) SetPath(v string) *MediaStreamCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillablePath(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetPixelFormat sets the "pixel_format" field.
func (_c *MediaStreamCreate) SetPixelFormat(v string) *MediaStreamCreate {
	_c.mutation.SetPixelFormat(v)
	return _c
}

// SetNillablePixelFormat sets the "pixel_format" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillablePixelFormat(v *string) *MediaStreamCreate {
	if v != nil {
		_c.SetPixelFormat(*v)
	}
	return _c
}

// SetBitRate sets the "bit_rate" field.
func (_c *MediaStreamCreate) SetBitRate(v int32) *MediaStreamCreate {
	_c.mutation.SetBitRate(v)
	return _c
}

// SetNillableBitRate sets the "bit_rate" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableBitRate(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetBitRate(*v)
	}
	return _c
}

// SetChannels sets the "channels" field.
func (_c *MediaStreamCreate) SetChannels(v int32) *MediaStreamCreate {
	_c.mutation.SetChannels(v)
	return _c
}

// SetNillableChannels sets the "channels" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableChannels(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetChannels(*v)
	}
	return _c
}

// SetSampleRate sets the "sample_rate" field.
func (_c *MediaStreamCreate) SetSampleRate(v int32) *MediaStreamCreate {
	_c.mutation.SetSampleRate(v)
	return _c
}

// SetNillableSampleRate sets the "sample_rate" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableSampleRate(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetSampleRate(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *MediaStreamCreate) SetWidth(v int32) *MediaStreamCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableWidth(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *MediaStreamCreate) SetHeight(v int32) *MediaStreamCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableHeight(v *int32) *MediaStreamCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *MediaStreamCreate) SetLevel(v float64) *MediaStreamCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableLevel(v *float64) *MediaStreamCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *MediaStreamCreate) SetIsDefault(v bool) *MediaStreamCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsDefault(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetIsForced sets the "is_forced" field.
func (_c *MediaStreamCreate) SetIsForced(v bool) *MediaStreamCreate {
	_c.mutation.SetIsForced(v)
	return _c
}

// SetNillableIsForced sets the "is_forced" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsForced(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsForced(*v)
	}
	return _c
}

// SetIsExternal sets the "is_external" field.
func (_c *MediaStreamCreate) SetIsExternal(v bool) *MediaStreamCreate {
	_c.mutation.SetIsExternal(v)
	return _c
}

// SetNillableIsExternal sets the "is_external" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsExternal(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsExternal(*v)
	}
	return _c
}

// SetIsInterlaced sets the "is_interlaced" field.
func (_c *MediaStreamCreate) SetIsInterlaced(v bool) *MediaStreamCreate {
	_c.mutation.SetIsInterlaced(v)
	return _c
}

// SetNillableIsInterlaced sets the "is_interlaced" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsInterlaced(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsInterlaced(*v)
	}
	return _c
}

// SetIsAnamorphic sets the "is_anamorphic" field.
func (_c *MediaStreamCreate) SetIsAnamorphic(v bool) *MediaStreamCreate {
	_c.mutation.SetIsAnamorphic(v)
	return _c
}

// SetNillableIsAnamorphic sets the "is_anamorphic" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsAnamorphic(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsAnamorphic(*v)
	}
	return _c
}

// SetIsHearingImpaired sets the "is_hearing_impaired" field.
func (_c *MediaStreamCreate) SetIsHearingImpaired(v bool) *MediaStreamCreate {
	_c.mutation.SetIsHearingImpaired(v)
	return _c
}

// SetNillableIsHearingImpaired sets the "is_hearing_impaired" field if the given value is not nil.
func (_c *MediaStreamCreate) SetNillableIsHearingImpaired(v *bool) *MediaStreamCreate {
	if v != nil {
		_c.SetIsHearingImpaired(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaStreamCreate) SetID(v uuid.UUID) *MediaStreamCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSource sets the "source" edge to the MediaSource entity.
func (_c *MediaStreamCreate) SetSource(v *MediaSource) *MediaStreamCreate {
	return _c.SetSourceID(v.ID)
}

// Mutation returns the MediaStreamMutation object of the builder.
func (_c *MediaStreamCreate) Mutation() *MediaStreamMutation {
	return _c.mutation
}

// Save creates the MediaStream in the database.
func (_c *MediaStreamCreate) Save(ctx context.Context) (*MediaStream, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaStreamCreate) SaveX(ctx context.Context) *MediaStream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaStreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaStreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaStreamCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediastream.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediastream.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Index(); !ok {
		v := mediastream.DefaultIndex
		_c.mutation.SetIndex(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := mediastream.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.IsForced(); !ok {
		v := mediastream.DefaultIsForced
		_c.mutation.SetIsForced(v)
	}
	if _, ok := _c.mutation.IsExternal(); !ok {
		v := mediastream.DefaultIsExternal
		_c.mutation.SetIsExternal(v)
	}
	if _, ok := _c.mutation.IsInterlaced(); !ok {
		v := mediastream.DefaultIsInterlaced
		_c.mutation.SetIsInterlaced(v)
	}
	if _, ok := _c.mutation.IsAnamorphic(); !ok {
		v := mediastream.DefaultIsAnamorphic
		_c.mutation.SetIsAnamorphic(v)
	}
	if _, ok := _c.mutation.IsHearingImpaired(); !ok {
		v := mediastream.DefaultIsHearingImpaired
		_c.mutation.SetIsHearingImpaired(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaStreamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`store: missing required field "MediaStream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`store: missing required field "MediaStream.updated_at"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`store: missing required field "MediaStream.source_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`store: missing required field "MediaStream.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := mediastream.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`store: validator failed for field "MediaStream.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.VideoRangeType(); ok {
		if err := mediastream.VideoRangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "video_range_type", err: fmt.Errorf(`store: validator failed for field "MediaStream.video_range_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`store: missing required field "MediaStream.index"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`store: missing required field "MediaStream.is_default"`)}
	}
	if _, ok := _c.mutation.IsForced(); !ok {
		return &ValidationError{Name: "is_forced", err: errors.New(`store: missing required field "MediaStream.is_forced"`)}
	}
	if _, ok := _c.mutation.IsExternal(); !ok {
		return &ValidationError{Name: "is_external", err: errors.New(`store: missing required field "MediaStream.is_external"`)}
	}
	if _, ok := _c.mutation.IsInterlaced(); !ok {
		return &ValidationError{Name: "is_interlaced", err: errors.New(`store: missing required field "MediaStream.is_interlaced"`)}
	}
	if _, ok := _c.mutation.IsAnamorphic(); !ok {
		return &ValidationError{Name: "is_anamorphic", err: errors.New(`store: missing required field "MediaStream.is_anamorphic"`)}
	}
	if _, ok := _c.mutation.IsHearingImpaired(); !ok {
		return &ValidationError{Name: "is_hearing_impaired", err: errors.New(`store: missing required field "MediaStream.is_hearing_impaired"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`store: missing required edge "MediaStream.source"`)}
	}
	return nil
}

func (_c *MediaStreamCreate) sqlSave(ctx context.Context) (*MediaStream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaStreamCreate) createSpec() (*MediaStream, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaStream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediastream.Table, sqlgraph.NewFieldSpec(mediastream.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediastream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediastream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(mediastream.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.VideoRangeType(); ok {
		_spec.SetField(mediastream.FieldVideoRangeType, field.TypeEnum, value)
		_node.VideoRangeType = value
	}
	if value, ok := _c.mutation.Index(); ok {
		_spec.SetField(mediastream.FieldIndex, field.TypeInt32, value)
		_node.Index = value
	}
	if value, ok := _c.mutation.Codec(); ok {
		_spec.SetField(mediastream.FieldCodec, field.TypeString, value)
		_node.Codec = value
	}
	if value, ok := _c.mutation.Profile(); ok {
		_spec.SetField(mediastream.FieldProfile, field.TypeString, value)
		_node.Profile = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(mediastream.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(mediastream.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(mediastream.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.PixelFormat(); ok {
		_spec.SetField(mediastream.FieldPixelFormat, field.TypeString, value)
		_node.PixelFormat = value
	}
	if value, ok := _c.mutation.BitRate(); ok {
		_spec.SetField(mediastream.FieldBitRate, field.TypeInt32, value)
		_node.BitRate = value
	}
	if value, ok := _c.mutation.Channels(); ok {
		_spec.SetField(mediastream.FieldChannels, field.TypeInt32, value)
		_node.Channels = value
	}
	if value, ok := _c.mutation.SampleRate(); ok {
		_spec.SetField(mediastream.FieldSampleRate, field.TypeInt32, value)
		_node.SampleRate = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(mediastream.FieldWidth, field.TypeInt32, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(mediastream.FieldHeight, field.TypeInt32, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(mediastream.FieldLevel, field.TypeFloat64, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(mediastream.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.IsForced(); ok {
		_spec.SetField(mediastream.FieldIsForced, field.TypeBool, value)
		_node.IsForced = value
	}
	if value, ok := _c.mutation.IsExternal(); ok {
		_spec.SetField(mediastream.FieldIsExternal, field.TypeBool, value)
		_node.IsExternal = value
	}
	if value, ok := _c.mutation.IsInterlaced(); ok {
		_spec.SetField(mediastream.FieldIsInterlaced, field.TypeBool, value)
		_node.IsInterlaced = value
	}
	if value, ok := _c.mutation.IsAnamorphic(); ok {
		_spec.SetField(mediastream.FieldIsAnamorphic, field.TypeBool, value)
		_node.IsAnamorphic = value
	}
	if value, ok := _c.mutation.IsHearingImpaired(); ok {
		_spec.SetField(mediastream.FieldIsHearingImpaired, field.TypeBool, value)
		_node.IsHearingImpaired = value
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediastream.SourceTable,
			Columns: []string{mediastream.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediasource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaStream.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaStreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaStreamCreate) OnConflict(opts ...sql.ConflictOption) *MediaStreamUpsertOne {
	_c.conflict = opts
	return &MediaStreamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaStreamCreate) OnConflictColumns(columns ...string) *MediaStreamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaStreamUpsertOne{
		create: _c,
	}
}

type (
	// MediaStreamUpsertOne is the builder for "upsert"-ing
	//  one MediaStream node.
	MediaStreamUpsertOne struct {
		create *MediaStreamCreate
	}

	// MediaStreamUpsert is the "OnConflict" setter.
	MediaStreamUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *MediaStreamUpsert) SetCreatedAt(v time.Time) *MediaStreamUpsert {
	u.Set(mediastream.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateCreatedAt() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaStreamUpsert) SetUpdatedAt(v time.Time) *MediaStreamUpsert {
	u.Set(mediastream.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateUpdatedAt() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldUpdatedAt)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *MediaStreamUpsert) SetSourceID(v uuid.UUID) *MediaStreamUpsert {
	u.Set(mediastream.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateSourceID() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldSourceID)
	return u
}

// SetKind sets the "kind" field.
func (u *MediaStreamUpsert) SetKind(v mediastream.Kind) *MediaStreamUpsert {
	u.Set(mediastream.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateKind() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldKind)
	return u
}

// SetVideoRangeType sets the "video_range_type" field.
func (u *MediaStreamUpsert) SetVideoRangeType(v mediastream.VideoRangeType) *MediaStreamUpsert {
	u.Set(mediastream.FieldVideoRangeType, v)
	return u
}

// UpdateVideoRangeType sets the "video_range_type" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateVideoRangeType() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldVideoRangeType)
	return u
}

// ClearVideoRangeType clears the value of the "video_range_type" field.
func (u *MediaStreamUpsert) ClearVideoRangeType() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldVideoRangeType)
	return u
}

// SetIndex sets the "index" field.
func (u *MediaStreamUpsert) SetIndex(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldIndex, v)
	return u
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIndex() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIndex)
	return u
}

// AddIndex adds v to the "index" field.
func (u *MediaStreamUpsert) AddIndex(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldIndex, v)
	return u
}

// SetCodec sets the "codec" field.
func (u *MediaStreamUpsert) SetCodec(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldCodec, v)
	return u
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateCodec() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldCodec)
	return u
}

// ClearCodec clears the value of the "codec" field.
func (u *MediaStreamUpsert) ClearCodec() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldCodec)
	return u
}

// SetProfile sets the "profile" field.
func (u *MediaStreamUpsert) SetProfile(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldProfile, v)
	return u
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateProfile() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldProfile)
	return u
}

// ClearProfile clears the value of the "profile" field.
func (u *MediaStreamUpsert) ClearProfile() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldProfile)
	return u
}

// SetLanguage sets the "language" field.
func (u *MediaStreamUpsert) SetLanguage(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateLanguage() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldLanguage)
	return u
}

// ClearLanguage clears the value of the "language" field.
func (u *MediaStreamUpsert) ClearLanguage() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldLanguage)
	return u
}

// SetTitle sets the "title" field.
func (u *MediaStreamUpsert) SetTitle(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateTitle() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *MediaStreamUpsert) ClearTitle() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldTitle)
	return u
}

// SetPath sets the "path" field.
func (u *MediaStreamUpsert) SetPath(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdatePath() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *MediaStreamUpsert) ClearPath() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldPath)
	return u
}

// SetPixelFormat sets the "pixel_format" field.
func (u *MediaStreamUpsert) SetPixelFormat(v string) *MediaStreamUpsert {
	u.Set(mediastream.FieldPixelFormat, v)
	return u
}

// UpdatePixelFormat sets the "pixel_format" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdatePixelFormat() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldPixelFormat)
	return u
}

// ClearPixelFormat clears the value of the "pixel_format" field.
func (u *MediaStreamUpsert) ClearPixelFormat() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldPixelFormat)
	return u
}

// SetBitRate sets the "bit_rate" field.
func (u *MediaStreamUpsert) SetBitRate(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldBitRate, v)
	return u
}

// UpdateBitRate sets the "bit_rate" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateBitRate() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldBitRate)
	return u
}

// AddBitRate adds v to the "bit_rate" field.
func (u *MediaStreamUpsert) AddBitRate(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldBitRate, v)
	return u
}

// ClearBitRate clears the value of the "bit_rate" field.
func (u *MediaStreamUpsert) ClearBitRate() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldBitRate)
	return u
}

// SetChannels sets the "channels" field.
func (u *MediaStreamUpsert) SetChannels(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldChannels, v)
	return u
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateChannels() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldChannels)
	return u
}

// AddChannels adds v to the "channels" field.
func (u *MediaStreamUpsert) AddChannels(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldChannels, v)
	return u
}

// ClearChannels clears the value of the "channels" field.
func (u *MediaStreamUpsert) ClearChannels() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldChannels)
	return u
}

// SetSampleRate sets the "sample_rate" field.
func (u *MediaStreamUpsert) SetSampleRate(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldSampleRate, v)
	return u
}

// UpdateSampleRate sets the "sample_rate" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateSampleRate() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldSampleRate)
	return u
}

// AddSampleRate adds v to the "sample_rate" field.
func (u *MediaStreamUpsert) AddSampleRate(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldSampleRate, v)
	return u
}

// ClearSampleRate clears the value of the "sample_rate" field.
func (u *MediaStreamUpsert) ClearSampleRate() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldSampleRate)
	return u
}

// SetWidth sets the "width" field.
func (u *MediaStreamUpsert) SetWidth(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateWidth() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *MediaStreamUpsert) AddWidth(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *MediaStreamUpsert) ClearWidth() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *MediaStreamUpsert) SetHeight(v int32) *MediaStreamUpsert {
	u.Set(mediastream.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateHeight() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *MediaStreamUpsert) AddHeight(v int32) *MediaStreamUpsert {
	u.Add(mediastream.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *MediaStreamUpsert) ClearHeight() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldHeight)
	return u
}

// SetLevel sets the "level" field.
func (u *MediaStreamUpsert) SetLevel(v float64) *MediaStreamUpsert {
	u.Set(mediastream.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateLevel() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldLevel)
	return u
}

// AddLevel adds v to the "level" field.
func (u *MediaStreamUpsert) AddLevel(v float64) *MediaStreamUpsert {
	u.Add(mediastream.FieldLevel, v)
	return u
}

// ClearLevel clears the value of the "level" field.
func (u *MediaStreamUpsert) ClearLevel() *MediaStreamUpsert {
	u.SetNull(mediastream.FieldLevel)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *MediaStreamUpsert) SetIsDefault(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsDefault() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsDefault)
	return u
}

// SetIsForced sets the "is_forced" field.
func (u *MediaStreamUpsert) SetIsForced(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsForced, v)
	return u
}

// UpdateIsForced sets the "is_forced" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsForced() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsForced)
	return u
}

// SetIsExternal sets the "is_external" field.
func (u *MediaStreamUpsert) SetIsExternal(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsExternal, v)
	return u
}

// UpdateIsExternal sets the "is_external" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsExternal() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsExternal)
	return u
}

// SetIsInterlaced sets the "is_interlaced" field.
func (u *MediaStreamUpsert) SetIsInterlaced(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsInterlaced, v)
	return u
}

// UpdateIsInterlaced sets the "is_interlaced" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsInterlaced() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsInterlaced)
	return u
}

// SetIsAnamorphic sets the "is_anamorphic" field.
func (u *MediaStreamUpsert) SetIsAnamorphic(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsAnamorphic, v)
	return u
}

// UpdateIsAnamorphic sets the "is_anamorphic" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsAnamorphic() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsAnamorphic)
	return u
}

// SetIsHearingImpaired sets the "is_hearing_impaired" field.
func (u *MediaStreamUpsert) SetIsHearingImpaired(v bool) *MediaStreamUpsert {
	u.Set(mediastream.FieldIsHearingImpaired, v)
	return u
}

// UpdateIsHearingImpaired sets the "is_hearing_impaired" field to the value that was provided on create.
func (u *MediaStreamUpsert) UpdateIsHearingImpaired() *MediaStreamUpsert {
	u.SetExcluded(mediastream.FieldIsHearingImpaired)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mediastream.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MediaStreamUpsertOne) UpdateNewValues() *MediaStreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(mediastream.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaStreamUpsertOne) Ignore() *MediaStreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaStreamUpsertOne) DoNothing() *MediaStreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaStreamCreate.OnConflict
// documentation for more info.
func (u *MediaStreamUpsertOne) Update(set func(*MediaStreamUpsert)) *MediaStreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaStreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MediaStreamUpsertOne) SetCreatedAt(v time.Time) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateCreatedAt() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaStreamUpsertOne) SetUpdatedAt(v time.Time) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateUpdatedAt() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourceID sets the "source_id" field.
func (u *MediaStreamUpsertOne) SetSourceID(v uuid.UUID) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateSourceID() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateSourceID()
	})
}

// SetKind sets the "kind" field.
func (u *MediaStreamUpsertOne) SetKind(v mediastream.Kind) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateKind() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateKind()
	})
}

// SetVideoRangeType sets the "video_range_type" field.
func (u *MediaStreamUpsertOne) SetVideoRangeType(v mediastream.VideoRangeType) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetVideoRangeType(v)
	})
}

// UpdateVideoRangeType sets the "video_range_type" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateVideoRangeType() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateVideoRangeType()
	})
}

// ClearVideoRangeType clears the value of the "video_range_type" field.
func (u *MediaStreamUpsertOne) ClearVideoRangeType() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearVideoRangeType()
	})
}

// SetIndex sets the "index" field.
func (u *MediaStreamUpsertOne) SetIndex(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *MediaStreamUpsertOne) AddIndex(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIndex() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIndex()
	})
}

// SetCodec sets the "codec" field.
func (u *MediaStreamUpsertOne) SetCodec(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetCodec(v)
	})
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateCodec() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateCodec()
	})
}

// ClearCodec clears the value of the "codec" field.
func (u *MediaStreamUpsertOne) ClearCodec() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearCodec()
	})
}

// SetProfile sets the "profile" field.
func (u *MediaStreamUpsertOne) SetProfile(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateProfile() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *MediaStreamUpsertOne) ClearProfile() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearProfile()
	})
}

// SetLanguage sets the "language" field.
func (u *MediaStreamUpsertOne) SetLanguage(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateLanguage() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateLanguage()
	})
}

// ClearLanguage clears the value of the "language" field.
func (u *MediaStreamUpsertOne) ClearLanguage() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearLanguage()
	})
}

// SetTitle sets the "title" field.
func (u *MediaStreamUpsertOne) SetTitle(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateTitle() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *MediaStreamUpsertOne) ClearTitle() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearTitle()
	})
}

// SetPath sets the "path" field.
func (u *MediaStreamUpsertOne) SetPath(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdatePath() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *MediaStreamUpsertOne) ClearPath() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearPath()
	})
}

// SetPixelFormat sets the "pixel_format" field.
func (u *MediaStreamUpsertOne) SetPixelFormat(v string) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetPixelFormat(v)
	})
}

// UpdatePixelFormat sets the "pixel_format" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdatePixelFormat() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdatePixelFormat()
	})
}

// ClearPixelFormat clears the value of the "pixel_format" field.
func (u *MediaStreamUpsertOne) ClearPixelFormat() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearPixelFormat()
	})
}

// SetBitRate sets the "bit_rate" field.
func (u *MediaStreamUpsertOne) SetBitRate(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetBitRate(v)
	})
}

// AddBitRate adds v to the "bit_rate" field.
func (u *MediaStreamUpsertOne) AddBitRate(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddBitRate(v)
	})
}

// UpdateBitRate sets the "bit_rate" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateBitRate() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateBitRate()
	})
}

// ClearBitRate clears the value of the "bit_rate" field.
func (u *MediaStreamUpsertOne) ClearBitRate() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearBitRate()
	})
}

// SetChannels sets the "channels" field.
func (u *MediaStreamUpsertOne) SetChannels(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetChannels(v)
	})
}

// AddChannels adds v to the "channels" field.
func (u *MediaStreamUpsertOne) AddChannels(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddChannels(v)
	})
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateChannels() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateChannels()
	})
}

// ClearChannels clears the value of the "channels" field.
func (u *MediaStreamUpsertOne) ClearChannels() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearChannels()
	})
}

// SetSampleRate sets the "sample_rate" field.
func (u *MediaStreamUpsertOne) SetSampleRate(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetSampleRate(v)
	})
}

// AddSampleRate adds v to the "sample_rate" field.
func (u *MediaStreamUpsertOne) AddSampleRate(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddSampleRate(v)
	})
}

// UpdateSampleRate sets the "sample_rate" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateSampleRate() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateSampleRate()
	})
}

// ClearSampleRate clears the value of the "sample_rate" field.
func (u *MediaStreamUpsertOne) ClearSampleRate() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearSampleRate()
	})
}

// SetWidth sets the "width" field.
func (u *MediaStreamUpsertOne) SetWidth(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *MediaStreamUpsertOne) AddWidth(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateWidth() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *MediaStreamUpsertOne) ClearWidth() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *MediaStreamUpsertOne) SetHeight(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *MediaStreamUpsertOne) AddHeight(v int32) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateHeight() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *MediaStreamUpsertOne) ClearHeight() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearHeight()
	})
}

// SetLevel sets the "level" field.
func (u *MediaStreamUpsertOne) SetLevel(v float64) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *MediaStreamUpsertOne) AddLevel(v float64) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateLevel() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateLevel()
	})
}

// ClearLevel clears the value of the "level" field.
func (u *MediaStreamUpsertOne) ClearLevel() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearLevel()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *MediaStreamUpsertOne) SetIsDefault(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsDefault() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsForced sets the "is_forced" field.
func (u *MediaStreamUpsertOne) SetIsForced(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsForced(v)
	})
}

// UpdateIsForced sets the "is_forced" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsForced() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsForced()
	})
}

// SetIsExternal sets the "is_external" field.
func (u *MediaStreamUpsertOne) SetIsExternal(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsExternal(v)
	})
}

// UpdateIsExternal sets the "is_external" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsExternal() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsExternal()
	})
}

// SetIsInterlaced sets the "is_interlaced" field.
func (u *MediaStreamUpsertOne) SetIsInterlaced(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsInterlaced(v)
	})
}

// UpdateIsInterlaced sets the "is_interlaced" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsInterlaced() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsInterlaced()
	})
}

// SetIsAnamorphic sets the "is_anamorphic" field.
func (u *MediaStreamUpsertOne) SetIsAnamorphic(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsAnamorphic(v)
	})
}

// UpdateIsAnamorphic sets the "is_anamorphic" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsAnamorphic() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsAnamorphic()
	})
}

// SetIsHearingImpaired sets the "is_hearing_impaired" field.
func (u *MediaStreamUpsertOne) SetIsHearingImpaired(v bool) *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsHearingImpaired(v)
	})
}

// UpdateIsHearingImpaired sets the "is_hearing_impaired" field to the value that was provided on create.
func (u *MediaStreamUpsertOne) UpdateIsHearingImpaired() *MediaStreamUpsertOne {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsHearingImpaired()
	})
}

// Exec executes the query.
func (u *MediaStreamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for MediaStreamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaStreamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaStreamUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("store: MediaStreamUpsertOne.ID is not supported by MySQL driver. Use MediaStreamUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaStreamUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaStreamCreateBulk is the builder for creating many MediaStream entities in bulk.
type MediaStreamCreateBulk struct {
	config
	err      error
	builders []*MediaStreamCreate
	conflict []sql.ConflictOption
}

// Save creates the MediaStream entities in the database.
func (_c *MediaStreamCreateBulk) Save(ctx context.Context) ([]*MediaStream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaStream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaStreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaStreamCreateBulk) SaveX(ctx context.Context) []*MediaStream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaStreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaStreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaStream.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaStreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaStreamCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaStreamUpsertBulk {
	_c.conflict = opts
	return &MediaStreamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaStreamCreateBulk) OnConflictColumns(columns ...string) *MediaStreamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaStreamUpsertBulk{
		create: _c,
	}
}

// MediaStreamUpsertBulk is the builder for "upsert"-ing
// a bulk of MediaStream nodes.
type MediaStreamUpsertBulk struct {
	create *MediaStreamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mediastream.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MediaStreamUpsertBulk) UpdateNewValues() *MediaStreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(mediastream.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaStream.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaStreamUpsertBulk) Ignore() *MediaStreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaStreamUpsertBulk) DoNothing() *MediaStreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaStreamCreateBulk.OnConflict
// documentation for more info.
func (u *MediaStreamUpsertBulk) Update(set func(*MediaStreamUpsert)) *MediaStreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaStreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MediaStreamUpsertBulk) SetCreatedAt(v time.Time) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateCreatedAt() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaStreamUpsertBulk) SetUpdatedAt(v time.Time) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateUpdatedAt() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourceID sets the "source_id" field.
func (u *MediaStreamUpsertBulk) SetSourceID(v uuid.UUID) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateSourceID() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateSourceID()
	})
}

// SetKind sets the "kind" field.
func (u *MediaStreamUpsertBulk) SetKind(v mediastream.Kind) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateKind() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateKind()
	})
}

// SetVideoRangeType sets the "video_range_type" field.
func (u *MediaStreamUpsertBulk) SetVideoRangeType(v mediastream.VideoRangeType) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetVideoRangeType(v)
	})
}

// UpdateVideoRangeType sets the "video_range_type" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateVideoRangeType() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateVideoRangeType()
	})
}

// ClearVideoRangeType clears the value of the "video_range_type" field.
func (u *MediaStreamUpsertBulk) ClearVideoRangeType() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearVideoRangeType()
	})
}

// SetIndex sets the "index" field.
func (u *MediaStreamUpsertBulk) SetIndex(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *MediaStreamUpsertBulk) AddIndex(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIndex() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIndex()
	})
}

// SetCodec sets the "codec" field.
func (u *MediaStreamUpsertBulk) SetCodec(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetCodec(v)
	})
}

// UpdateCodec sets the "codec" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateCodec() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateCodec()
	})
}

// ClearCodec clears the value of the "codec" field.
func (u *MediaStreamUpsertBulk) ClearCodec() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearCodec()
	})
}

// SetProfile sets the "profile" field.
func (u *MediaStreamUpsertBulk) SetProfile(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateProfile() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *MediaStreamUpsertBulk) ClearProfile() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearProfile()
	})
}

// SetLanguage sets the "language" field.
func (u *MediaStreamUpsertBulk) SetLanguage(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateLanguage() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateLanguage()
	})
}

// ClearLanguage clears the value of the "language" field.
func (u *MediaStreamUpsertBulk) ClearLanguage() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearLanguage()
	})
}

// SetTitle sets the "title" field.
func (u *MediaStreamUpsertBulk) SetTitle(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateTitle() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *MediaStreamUpsertBulk) ClearTitle() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearTitle()
	})
}

// SetPath sets the "path" field.
func (u *MediaStreamUpsertBulk) SetPath(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdatePath() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *MediaStreamUpsertBulk) ClearPath() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearPath()
	})
}

// SetPixelFormat sets the "pixel_format" field.
func (u *MediaStreamUpsertBulk) SetPixelFormat(v string) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetPixelFormat(v)
	})
}

// UpdatePixelFormat sets the "pixel_format" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdatePixelFormat() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdatePixelFormat()
	})
}

// ClearPixelFormat clears the value of the "pixel_format" field.
func (u *MediaStreamUpsertBulk) ClearPixelFormat() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearPixelFormat()
	})
}

// SetBitRate sets the "bit_rate" field.
func (u *MediaStreamUpsertBulk) SetBitRate(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetBitRate(v)
	})
}

// AddBitRate adds v to the "bit_rate" field.
func (u *MediaStreamUpsertBulk) AddBitRate(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddBitRate(v)
	})
}

// UpdateBitRate sets the "bit_rate" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateBitRate() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateBitRate()
	})
}

// ClearBitRate clears the value of the "bit_rate" field.
func (u *MediaStreamUpsertBulk) ClearBitRate() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearBitRate()
	})
}

// SetChannels sets the "channels" field.
func (u *MediaStreamUpsertBulk) SetChannels(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetChannels(v)
	})
}

// AddChannels adds v to the "channels" field.
func (u *MediaStreamUpsertBulk) AddChannels(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddChannels(v)
	})
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateChannels() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateChannels()
	})
}

// ClearChannels clears the value of the "channels" field.
func (u *MediaStreamUpsertBulk) ClearChannels() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearChannels()
	})
}

// SetSampleRate sets the "sample_rate" field.
func (u *MediaStreamUpsertBulk) SetSampleRate(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetSampleRate(v)
	})
}

// AddSampleRate adds v to the "sample_rate" field.
func (u *MediaStreamUpsertBulk) AddSampleRate(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddSampleRate(v)
	})
}

// UpdateSampleRate sets the "sample_rate" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateSampleRate() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateSampleRate()
	})
}

// ClearSampleRate clears the value of the "sample_rate" field.
func (u *MediaStreamUpsertBulk) ClearSampleRate() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearSampleRate()
	})
}

// SetWidth sets the "width" field.
func (u *MediaStreamUpsertBulk) SetWidth(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *MediaStreamUpsertBulk) AddWidth(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateWidth() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *MediaStreamUpsertBulk) ClearWidth() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *MediaStreamUpsertBulk) SetHeight(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *MediaStreamUpsertBulk) AddHeight(v int32) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateHeight() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *MediaStreamUpsertBulk) ClearHeight() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearHeight()
	})
}

// SetLevel sets the "level" field.
func (u *MediaStreamUpsertBulk) SetLevel(v float64) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *MediaStreamUpsertBulk) AddLevel(v float64) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateLevel() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateLevel()
	})
}

// ClearLevel clears the value of the "level" field.
func (u *MediaStreamUpsertBulk) ClearLevel() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.ClearLevel()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *MediaStreamUpsertBulk) SetIsDefault(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsDefault() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsForced sets the "is_forced" field.
func (u *MediaStreamUpsertBulk) SetIsForced(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsForced(v)
	})
}

// UpdateIsForced sets the "is_forced" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsForced() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsForced()
	})
}

// SetIsExternal sets the "is_external" field.
func (u *MediaStreamUpsertBulk) SetIsExternal(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsExternal(v)
	})
}

// UpdateIsExternal sets the "is_external" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsExternal() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsExternal()
	})
}

// SetIsInterlaced sets the "is_interlaced" field.
func (u *MediaStreamUpsertBulk) SetIsInterlaced(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsInterlaced(v)
	})
}

// UpdateIsInterlaced sets the "is_interlaced" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsInterlaced() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsInterlaced()
	})
}

// SetIsAnamorphic sets the "is_anamorphic" field.
func (u *MediaStreamUpsertBulk) SetIsAnamorphic(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsAnamorphic(v)
	})
}

// UpdateIsAnamorphic sets the "is_anamorphic" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsAnamorphic() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsAnamorphic()
	})
}

// SetIsHearingImpaired sets the "is_hearing_impaired" field.
func (u *MediaStreamUpsertBulk) SetIsHearingImpaired(v bool) *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.SetIsHearingImpaired(v)
	})
}

// UpdateIsHearingImpaired sets the "is_hearing_impaired" field to the value that was provided on create.
func (u *MediaStreamUpsertBulk) UpdateIsHearingImpaired() *MediaStreamUpsertBulk {
	return u.Update(func(s *MediaStreamUpsert) {
		s.UpdateIsHearingImpaired()
	})
}

// Exec executes the query.
func (u *MediaStreamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("store: OnConflict was set for builder %d. Set it on the MediaStreamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for MediaStreamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaStreamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
