// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/FreekingDean/gojellyfin/internal/store/predicate"
	"github.com/FreekingDean/gojellyfin/internal/store/user"
	"github.com/FreekingDean/gojellyfin/internal/store/userconfiguration"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser              = "User"
	TypeUserConfiguration = "UserConfiguration"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	created_at           *time.Time
	updated_at           *time.Time
	name                 *string
	username             *string
	password_hash        *string
	clearedFields        map[string]struct{}
	configuration        map[uuid.UUID]struct{}
	removedconfiguration map[uuid.UUID]struct{}
	clearedconfiguration bool
	done                 bool
	oldValue             func(context.Context) (*User, error)
	predicates           []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id uuid.UUID) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("store: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetPasswordHash sets the "password_hash" field.
func (m *UserMutation) SetPasswordHash(s string) {
	m.password_hash = &s
}

// PasswordHash returns the value of the "password_hash" field in the mutation.
func (m *UserMutation) PasswordHash() (r string, exists bool) {
	v := m.password_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldPasswordHash returns the old "password_hash" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPasswordHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPasswordHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPasswordHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPasswordHash: %w", err)
	}
	return oldValue.PasswordHash, nil
}

// ResetPasswordHash resets all changes to the "password_hash" field.
func (m *UserMutation) ResetPasswordHash() {
	m.password_hash = nil
}

// AddConfigurationIDs adds the "configuration" edge to the UserConfiguration entity by ids.
func (m *UserMutation) AddConfigurationIDs(ids ...uuid.UUID) {
	if m.configuration == nil {
		m.configuration = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.configuration[ids[i]] = struct{}{}
	}
}

// ClearConfiguration clears the "configuration" edge to the UserConfiguration entity.
func (m *UserMutation) ClearConfiguration() {
	m.clearedconfiguration = true
}

// ConfigurationCleared reports if the "configuration" edge to the UserConfiguration entity was cleared.
func (m *UserMutation) ConfigurationCleared() bool {
	return m.clearedconfiguration
}

// RemoveConfigurationIDs removes the "configuration" edge to the UserConfiguration entity by IDs.
func (m *UserMutation) RemoveConfigurationIDs(ids ...uuid.UUID) {
	if m.removedconfiguration == nil {
		m.removedconfiguration = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.configuration, ids[i])
		m.removedconfiguration[ids[i]] = struct{}{}
	}
}

// RemovedConfiguration returns the removed IDs of the "configuration" edge to the UserConfiguration entity.
func (m *UserMutation) RemovedConfigurationIDs() (ids []uuid.UUID) {
	for id := range m.removedconfiguration {
		ids = append(ids, id)
	}
	return
}

// ConfigurationIDs returns the "configuration" edge IDs in the mutation.
func (m *UserMutation) ConfigurationIDs() (ids []uuid.UUID) {
	for id := range m.configuration {
		ids = append(ids, id)
	}
	return
}

// ResetConfiguration resets all changes to the "configuration" edge.
func (m *UserMutation) ResetConfiguration() {
	m.configuration = nil
	m.clearedconfiguration = false
	m.removedconfiguration = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.password_hash != nil {
		fields = append(fields, user.FieldPasswordHash)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	case user.FieldName:
		return m.Name()
	case user.FieldUsername:
		return m.Username()
	case user.FieldPasswordHash:
		return m.PasswordHash()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldPasswordHash:
		return m.OldPasswordHash(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldPasswordHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPasswordHash(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldPasswordHash:
		m.ResetPasswordHash()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.configuration != nil {
		edges = append(edges, user.EdgeConfiguration)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeConfiguration:
		ids := make([]ent.Value, 0, len(m.configuration))
		for id := range m.configuration {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedconfiguration != nil {
		edges = append(edges, user.EdgeConfiguration)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeConfiguration:
		ids := make([]ent.Value, 0, len(m.removedconfiguration))
		for id := range m.removedconfiguration {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedconfiguration {
		edges = append(edges, user.EdgeConfiguration)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeConfiguration:
		return m.clearedconfiguration
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeConfiguration:
		m.ResetConfiguration()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// UserConfigurationMutation represents an operation that mutates the UserConfiguration nodes in the graph.
type UserConfigurationMutation struct {
	config
	op                            Op
	typ                           string
	id                            *uuid.UUID
	created_at                    *time.Time
	updated_at                    *time.Time
	cast_receiver_id              *string
	audio_language_preference     *userconfiguration.AudioLanguagePreference
	play_default_audio_track      *bool
	subtitle_language_preference  *userconfiguration.SubtitleLanguagePreference
	subtitle_mode                 *userconfiguration.SubtitleMode
	gropued_folders               *[]string
	appendgropued_folders         []string
	ordered_views                 *[]string
	appendordered_views           []string
	latest_items_excludes         *[]string
	appendlatest_items_excludes   []string
	my_media_excludes             *[]string
	appendmy_media_excludes       []string
	display_missing_episodes      *bool
	display_collections_view      *bool
	enabled_local_password        *bool
	hide_played_in_latest         *bool
	remember_audio_selections     *bool
	enable_next_episode_auto_play *bool
	clearedFields                 map[string]struct{}
	user                          *uuid.UUID
	cleareduser                   bool
	done                          bool
	oldValue                      func(context.Context) (*UserConfiguration, error)
	predicates                    []predicate.UserConfiguration
}

var _ ent.Mutation = (*UserConfigurationMutation)(nil)

// userconfigurationOption allows management of the mutation configuration using functional options.
type userconfigurationOption func(*UserConfigurationMutation)

// newUserConfigurationMutation creates new mutation for the UserConfiguration entity.
func newUserConfigurationMutation(c config, op Op, opts ...userconfigurationOption) *UserConfigurationMutation {
	m := &UserConfigurationMutation{
		config:        c,
		op:            op,
		typ:           TypeUserConfiguration,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserConfigurationID sets the ID field of the mutation.
func withUserConfigurationID(id uuid.UUID) userconfigurationOption {
	return func(m *UserConfigurationMutation) {
		var (
			err   error
			once  sync.Once
			value *UserConfiguration
		)
		m.oldValue = func(ctx context.Context) (*UserConfiguration, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserConfiguration.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserConfiguration sets the old UserConfiguration of the mutation.
func withUserConfiguration(node *UserConfiguration) userconfigurationOption {
	return func(m *UserConfigurationMutation) {
		m.oldValue = func(context.Context) (*UserConfiguration, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserConfigurationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserConfigurationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("store: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of UserConfiguration entities.
func (m *UserConfigurationMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserConfigurationMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserConfigurationMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserConfiguration.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *UserConfigurationMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserConfigurationMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserConfigurationMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserConfigurationMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserConfigurationMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserConfigurationMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetCastReceiverID sets the "cast_receiver_id" field.
func (m *UserConfigurationMutation) SetCastReceiverID(s string) {
	m.cast_receiver_id = &s
}

// CastReceiverID returns the value of the "cast_receiver_id" field in the mutation.
func (m *UserConfigurationMutation) CastReceiverID() (r string, exists bool) {
	v := m.cast_receiver_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCastReceiverID returns the old "cast_receiver_id" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldCastReceiverID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCastReceiverID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCastReceiverID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCastReceiverID: %w", err)
	}
	return oldValue.CastReceiverID, nil
}

// ResetCastReceiverID resets all changes to the "cast_receiver_id" field.
func (m *UserConfigurationMutation) ResetCastReceiverID() {
	m.cast_receiver_id = nil
}

// SetAudioLanguagePreference sets the "audio_language_preference" field.
func (m *UserConfigurationMutation) SetAudioLanguagePreference(ulp userconfiguration.AudioLanguagePreference) {
	m.audio_language_preference = &ulp
}

// AudioLanguagePreference returns the value of the "audio_language_preference" field in the mutation.
func (m *UserConfigurationMutation) AudioLanguagePreference() (r userconfiguration.AudioLanguagePreference, exists bool) {
	v := m.audio_language_preference
	if v == nil {
		return
	}
	return *v, true
}

// OldAudioLanguagePreference returns the old "audio_language_preference" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldAudioLanguagePreference(ctx context.Context) (v userconfiguration.AudioLanguagePreference, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAudioLanguagePreference is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAudioLanguagePreference requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAudioLanguagePreference: %w", err)
	}
	return oldValue.AudioLanguagePreference, nil
}

// ResetAudioLanguagePreference resets all changes to the "audio_language_preference" field.
func (m *UserConfigurationMutation) ResetAudioLanguagePreference() {
	m.audio_language_preference = nil
}

// SetPlayDefaultAudioTrack sets the "play_default_audio_track" field.
func (m *UserConfigurationMutation) SetPlayDefaultAudioTrack(b bool) {
	m.play_default_audio_track = &b
}

// PlayDefaultAudioTrack returns the value of the "play_default_audio_track" field in the mutation.
func (m *UserConfigurationMutation) PlayDefaultAudioTrack() (r bool, exists bool) {
	v := m.play_default_audio_track
	if v == nil {
		return
	}
	return *v, true
}

// OldPlayDefaultAudioTrack returns the old "play_default_audio_track" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldPlayDefaultAudioTrack(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlayDefaultAudioTrack is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlayDefaultAudioTrack requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlayDefaultAudioTrack: %w", err)
	}
	return oldValue.PlayDefaultAudioTrack, nil
}

// ResetPlayDefaultAudioTrack resets all changes to the "play_default_audio_track" field.
func (m *UserConfigurationMutation) ResetPlayDefaultAudioTrack() {
	m.play_default_audio_track = nil
}

// SetSubtitleLanguagePreference sets the "subtitle_language_preference" field.
func (m *UserConfigurationMutation) SetSubtitleLanguagePreference(ulp userconfiguration.SubtitleLanguagePreference) {
	m.subtitle_language_preference = &ulp
}

// SubtitleLanguagePreference returns the value of the "subtitle_language_preference" field in the mutation.
func (m *UserConfigurationMutation) SubtitleLanguagePreference() (r userconfiguration.SubtitleLanguagePreference, exists bool) {
	v := m.subtitle_language_preference
	if v == nil {
		return
	}
	return *v, true
}

// OldSubtitleLanguagePreference returns the old "subtitle_language_preference" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldSubtitleLanguagePreference(ctx context.Context) (v userconfiguration.SubtitleLanguagePreference, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubtitleLanguagePreference is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubtitleLanguagePreference requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubtitleLanguagePreference: %w", err)
	}
	return oldValue.SubtitleLanguagePreference, nil
}

// ResetSubtitleLanguagePreference resets all changes to the "subtitle_language_preference" field.
func (m *UserConfigurationMutation) ResetSubtitleLanguagePreference() {
	m.subtitle_language_preference = nil
}

// SetSubtitleMode sets the "subtitle_mode" field.
func (m *UserConfigurationMutation) SetSubtitleMode(um userconfiguration.SubtitleMode) {
	m.subtitle_mode = &um
}

// SubtitleMode returns the value of the "subtitle_mode" field in the mutation.
func (m *UserConfigurationMutation) SubtitleMode() (r userconfiguration.SubtitleMode, exists bool) {
	v := m.subtitle_mode
	if v == nil {
		return
	}
	return *v, true
}

// OldSubtitleMode returns the old "subtitle_mode" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldSubtitleMode(ctx context.Context) (v userconfiguration.SubtitleMode, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubtitleMode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubtitleMode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubtitleMode: %w", err)
	}
	return oldValue.SubtitleMode, nil
}

// ResetSubtitleMode resets all changes to the "subtitle_mode" field.
func (m *UserConfigurationMutation) ResetSubtitleMode() {
	m.subtitle_mode = nil
}

// SetGropuedFolders sets the "gropued_folders" field.
func (m *UserConfigurationMutation) SetGropuedFolders(s []string) {
	m.gropued_folders = &s
	m.appendgropued_folders = nil
}

// GropuedFolders returns the value of the "gropued_folders" field in the mutation.
func (m *UserConfigurationMutation) GropuedFolders() (r []string, exists bool) {
	v := m.gropued_folders
	if v == nil {
		return
	}
	return *v, true
}

// OldGropuedFolders returns the old "gropued_folders" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldGropuedFolders(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGropuedFolders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGropuedFolders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGropuedFolders: %w", err)
	}
	return oldValue.GropuedFolders, nil
}

// AppendGropuedFolders adds s to the "gropued_folders" field.
func (m *UserConfigurationMutation) AppendGropuedFolders(s []string) {
	m.appendgropued_folders = append(m.appendgropued_folders, s...)
}

// AppendedGropuedFolders returns the list of values that were appended to the "gropued_folders" field in this mutation.
func (m *UserConfigurationMutation) AppendedGropuedFolders() ([]string, bool) {
	if len(m.appendgropued_folders) == 0 {
		return nil, false
	}
	return m.appendgropued_folders, true
}

// ResetGropuedFolders resets all changes to the "gropued_folders" field.
func (m *UserConfigurationMutation) ResetGropuedFolders() {
	m.gropued_folders = nil
	m.appendgropued_folders = nil
}

// SetOrderedViews sets the "ordered_views" field.
func (m *UserConfigurationMutation) SetOrderedViews(s []string) {
	m.ordered_views = &s
	m.appendordered_views = nil
}

// OrderedViews returns the value of the "ordered_views" field in the mutation.
func (m *UserConfigurationMutation) OrderedViews() (r []string, exists bool) {
	v := m.ordered_views
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderedViews returns the old "ordered_views" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldOrderedViews(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrderedViews is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrderedViews requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderedViews: %w", err)
	}
	return oldValue.OrderedViews, nil
}

// AppendOrderedViews adds s to the "ordered_views" field.
func (m *UserConfigurationMutation) AppendOrderedViews(s []string) {
	m.appendordered_views = append(m.appendordered_views, s...)
}

// AppendedOrderedViews returns the list of values that were appended to the "ordered_views" field in this mutation.
func (m *UserConfigurationMutation) AppendedOrderedViews() ([]string, bool) {
	if len(m.appendordered_views) == 0 {
		return nil, false
	}
	return m.appendordered_views, true
}

// ResetOrderedViews resets all changes to the "ordered_views" field.
func (m *UserConfigurationMutation) ResetOrderedViews() {
	m.ordered_views = nil
	m.appendordered_views = nil
}

// SetLatestItemsExcludes sets the "latest_items_excludes" field.
func (m *UserConfigurationMutation) SetLatestItemsExcludes(s []string) {
	m.latest_items_excludes = &s
	m.appendlatest_items_excludes = nil
}

// LatestItemsExcludes returns the value of the "latest_items_excludes" field in the mutation.
func (m *UserConfigurationMutation) LatestItemsExcludes() (r []string, exists bool) {
	v := m.latest_items_excludes
	if v == nil {
		return
	}
	return *v, true
}

// OldLatestItemsExcludes returns the old "latest_items_excludes" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldLatestItemsExcludes(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLatestItemsExcludes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLatestItemsExcludes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLatestItemsExcludes: %w", err)
	}
	return oldValue.LatestItemsExcludes, nil
}

// AppendLatestItemsExcludes adds s to the "latest_items_excludes" field.
func (m *UserConfigurationMutation) AppendLatestItemsExcludes(s []string) {
	m.appendlatest_items_excludes = append(m.appendlatest_items_excludes, s...)
}

// AppendedLatestItemsExcludes returns the list of values that were appended to the "latest_items_excludes" field in this mutation.
func (m *UserConfigurationMutation) AppendedLatestItemsExcludes() ([]string, bool) {
	if len(m.appendlatest_items_excludes) == 0 {
		return nil, false
	}
	return m.appendlatest_items_excludes, true
}

// ResetLatestItemsExcludes resets all changes to the "latest_items_excludes" field.
func (m *UserConfigurationMutation) ResetLatestItemsExcludes() {
	m.latest_items_excludes = nil
	m.appendlatest_items_excludes = nil
}

// SetMyMediaExcludes sets the "my_media_excludes" field.
func (m *UserConfigurationMutation) SetMyMediaExcludes(s []string) {
	m.my_media_excludes = &s
	m.appendmy_media_excludes = nil
}

// MyMediaExcludes returns the value of the "my_media_excludes" field in the mutation.
func (m *UserConfigurationMutation) MyMediaExcludes() (r []string, exists bool) {
	v := m.my_media_excludes
	if v == nil {
		return
	}
	return *v, true
}

// OldMyMediaExcludes returns the old "my_media_excludes" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldMyMediaExcludes(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMyMediaExcludes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMyMediaExcludes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMyMediaExcludes: %w", err)
	}
	return oldValue.MyMediaExcludes, nil
}

// AppendMyMediaExcludes adds s to the "my_media_excludes" field.
func (m *UserConfigurationMutation) AppendMyMediaExcludes(s []string) {
	m.appendmy_media_excludes = append(m.appendmy_media_excludes, s...)
}

// AppendedMyMediaExcludes returns the list of values that were appended to the "my_media_excludes" field in this mutation.
func (m *UserConfigurationMutation) AppendedMyMediaExcludes() ([]string, bool) {
	if len(m.appendmy_media_excludes) == 0 {
		return nil, false
	}
	return m.appendmy_media_excludes, true
}

// ResetMyMediaExcludes resets all changes to the "my_media_excludes" field.
func (m *UserConfigurationMutation) ResetMyMediaExcludes() {
	m.my_media_excludes = nil
	m.appendmy_media_excludes = nil
}

// SetDisplayMissingEpisodes sets the "display_missing_episodes" field.
func (m *UserConfigurationMutation) SetDisplayMissingEpisodes(b bool) {
	m.display_missing_episodes = &b
}

// DisplayMissingEpisodes returns the value of the "display_missing_episodes" field in the mutation.
func (m *UserConfigurationMutation) DisplayMissingEpisodes() (r bool, exists bool) {
	v := m.display_missing_episodes
	if v == nil {
		return
	}
	return *v, true
}

// OldDisplayMissingEpisodes returns the old "display_missing_episodes" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldDisplayMissingEpisodes(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDisplayMissingEpisodes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDisplayMissingEpisodes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDisplayMissingEpisodes: %w", err)
	}
	return oldValue.DisplayMissingEpisodes, nil
}

// ResetDisplayMissingEpisodes resets all changes to the "display_missing_episodes" field.
func (m *UserConfigurationMutation) ResetDisplayMissingEpisodes() {
	m.display_missing_episodes = nil
}

// SetDisplayCollectionsView sets the "display_collections_view" field.
func (m *UserConfigurationMutation) SetDisplayCollectionsView(b bool) {
	m.display_collections_view = &b
}

// DisplayCollectionsView returns the value of the "display_collections_view" field in the mutation.
func (m *UserConfigurationMutation) DisplayCollectionsView() (r bool, exists bool) {
	v := m.display_collections_view
	if v == nil {
		return
	}
	return *v, true
}

// OldDisplayCollectionsView returns the old "display_collections_view" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldDisplayCollectionsView(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDisplayCollectionsView is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDisplayCollectionsView requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDisplayCollectionsView: %w", err)
	}
	return oldValue.DisplayCollectionsView, nil
}

// ResetDisplayCollectionsView resets all changes to the "display_collections_view" field.
func (m *UserConfigurationMutation) ResetDisplayCollectionsView() {
	m.display_collections_view = nil
}

// SetEnabledLocalPassword sets the "enabled_local_password" field.
func (m *UserConfigurationMutation) SetEnabledLocalPassword(b bool) {
	m.enabled_local_password = &b
}

// EnabledLocalPassword returns the value of the "enabled_local_password" field in the mutation.
func (m *UserConfigurationMutation) EnabledLocalPassword() (r bool, exists bool) {
	v := m.enabled_local_password
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabledLocalPassword returns the old "enabled_local_password" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldEnabledLocalPassword(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabledLocalPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabledLocalPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabledLocalPassword: %w", err)
	}
	return oldValue.EnabledLocalPassword, nil
}

// ResetEnabledLocalPassword resets all changes to the "enabled_local_password" field.
func (m *UserConfigurationMutation) ResetEnabledLocalPassword() {
	m.enabled_local_password = nil
}

// SetHidePlayedInLatest sets the "hide_played_in_latest" field.
func (m *UserConfigurationMutation) SetHidePlayedInLatest(b bool) {
	m.hide_played_in_latest = &b
}

// HidePlayedInLatest returns the value of the "hide_played_in_latest" field in the mutation.
func (m *UserConfigurationMutation) HidePlayedInLatest() (r bool, exists bool) {
	v := m.hide_played_in_latest
	if v == nil {
		return
	}
	return *v, true
}

// OldHidePlayedInLatest returns the old "hide_played_in_latest" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldHidePlayedInLatest(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHidePlayedInLatest is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHidePlayedInLatest requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHidePlayedInLatest: %w", err)
	}
	return oldValue.HidePlayedInLatest, nil
}

// ResetHidePlayedInLatest resets all changes to the "hide_played_in_latest" field.
func (m *UserConfigurationMutation) ResetHidePlayedInLatest() {
	m.hide_played_in_latest = nil
}

// SetRememberAudioSelections sets the "remember_audio_selections" field.
func (m *UserConfigurationMutation) SetRememberAudioSelections(b bool) {
	m.remember_audio_selections = &b
}

// RememberAudioSelections returns the value of the "remember_audio_selections" field in the mutation.
func (m *UserConfigurationMutation) RememberAudioSelections() (r bool, exists bool) {
	v := m.remember_audio_selections
	if v == nil {
		return
	}
	return *v, true
}

// OldRememberAudioSelections returns the old "remember_audio_selections" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldRememberAudioSelections(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRememberAudioSelections is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRememberAudioSelections requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRememberAudioSelections: %w", err)
	}
	return oldValue.RememberAudioSelections, nil
}

// ResetRememberAudioSelections resets all changes to the "remember_audio_selections" field.
func (m *UserConfigurationMutation) ResetRememberAudioSelections() {
	m.remember_audio_selections = nil
}

// SetEnableNextEpisodeAutoPlay sets the "enable_next_episode_auto_play" field.
func (m *UserConfigurationMutation) SetEnableNextEpisodeAutoPlay(b bool) {
	m.enable_next_episode_auto_play = &b
}

// EnableNextEpisodeAutoPlay returns the value of the "enable_next_episode_auto_play" field in the mutation.
func (m *UserConfigurationMutation) EnableNextEpisodeAutoPlay() (r bool, exists bool) {
	v := m.enable_next_episode_auto_play
	if v == nil {
		return
	}
	return *v, true
}

// OldEnableNextEpisodeAutoPlay returns the old "enable_next_episode_auto_play" field's value of the UserConfiguration entity.
// If the UserConfiguration object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserConfigurationMutation) OldEnableNextEpisodeAutoPlay(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnableNextEpisodeAutoPlay is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnableNextEpisodeAutoPlay requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnableNextEpisodeAutoPlay: %w", err)
	}
	return oldValue.EnableNextEpisodeAutoPlay, nil
}

// ResetEnableNextEpisodeAutoPlay resets all changes to the "enable_next_episode_auto_play" field.
func (m *UserConfigurationMutation) ResetEnableNextEpisodeAutoPlay() {
	m.enable_next_episode_auto_play = nil
}

// SetUserID sets the "user" edge to the User entity by id.
func (m *UserConfigurationMutation) SetUserID(id uuid.UUID) {
	m.user = &id
}

// ClearUser clears the "user" edge to the User entity.
func (m *UserConfigurationMutation) ClearUser() {
	m.cleareduser = true
}

// UserCleared reports if the "user" edge to the User entity was cleared.
func (m *UserConfigurationMutation) UserCleared() bool {
	return m.cleareduser
}

// UserID returns the "user" edge ID in the mutation.
func (m *UserConfigurationMutation) UserID() (id uuid.UUID, exists bool) {
	if m.user != nil {
		return *m.user, true
	}
	return
}

// UserIDs returns the "user" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *UserConfigurationMutation) UserIDs() (ids []uuid.UUID) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser resets all changes to the "user" edge.
func (m *UserConfigurationMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// Where appends a list predicates to the UserConfigurationMutation builder.
func (m *UserConfigurationMutation) Where(ps ...predicate.UserConfiguration) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserConfigurationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserConfigurationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserConfiguration, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserConfigurationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserConfigurationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserConfiguration).
func (m *UserConfigurationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserConfigurationMutation) Fields() []string {
	fields := make([]string, 0, 17)
	if m.created_at != nil {
		fields = append(fields, userconfiguration.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, userconfiguration.FieldUpdatedAt)
	}
	if m.cast_receiver_id != nil {
		fields = append(fields, userconfiguration.FieldCastReceiverID)
	}
	if m.audio_language_preference != nil {
		fields = append(fields, userconfiguration.FieldAudioLanguagePreference)
	}
	if m.play_default_audio_track != nil {
		fields = append(fields, userconfiguration.FieldPlayDefaultAudioTrack)
	}
	if m.subtitle_language_preference != nil {
		fields = append(fields, userconfiguration.FieldSubtitleLanguagePreference)
	}
	if m.subtitle_mode != nil {
		fields = append(fields, userconfiguration.FieldSubtitleMode)
	}
	if m.gropued_folders != nil {
		fields = append(fields, userconfiguration.FieldGropuedFolders)
	}
	if m.ordered_views != nil {
		fields = append(fields, userconfiguration.FieldOrderedViews)
	}
	if m.latest_items_excludes != nil {
		fields = append(fields, userconfiguration.FieldLatestItemsExcludes)
	}
	if m.my_media_excludes != nil {
		fields = append(fields, userconfiguration.FieldMyMediaExcludes)
	}
	if m.display_missing_episodes != nil {
		fields = append(fields, userconfiguration.FieldDisplayMissingEpisodes)
	}
	if m.display_collections_view != nil {
		fields = append(fields, userconfiguration.FieldDisplayCollectionsView)
	}
	if m.enabled_local_password != nil {
		fields = append(fields, userconfiguration.FieldEnabledLocalPassword)
	}
	if m.hide_played_in_latest != nil {
		fields = append(fields, userconfiguration.FieldHidePlayedInLatest)
	}
	if m.remember_audio_selections != nil {
		fields = append(fields, userconfiguration.FieldRememberAudioSelections)
	}
	if m.enable_next_episode_auto_play != nil {
		fields = append(fields, userconfiguration.FieldEnableNextEpisodeAutoPlay)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserConfigurationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userconfiguration.FieldCreatedAt:
		return m.CreatedAt()
	case userconfiguration.FieldUpdatedAt:
		return m.UpdatedAt()
	case userconfiguration.FieldCastReceiverID:
		return m.CastReceiverID()
	case userconfiguration.FieldAudioLanguagePreference:
		return m.AudioLanguagePreference()
	case userconfiguration.FieldPlayDefaultAudioTrack:
		return m.PlayDefaultAudioTrack()
	case userconfiguration.FieldSubtitleLanguagePreference:
		return m.SubtitleLanguagePreference()
	case userconfiguration.FieldSubtitleMode:
		return m.SubtitleMode()
	case userconfiguration.FieldGropuedFolders:
		return m.GropuedFolders()
	case userconfiguration.FieldOrderedViews:
		return m.OrderedViews()
	case userconfiguration.FieldLatestItemsExcludes:
		return m.LatestItemsExcludes()
	case userconfiguration.FieldMyMediaExcludes:
		return m.MyMediaExcludes()
	case userconfiguration.FieldDisplayMissingEpisodes:
		return m.DisplayMissingEpisodes()
	case userconfiguration.FieldDisplayCollectionsView:
		return m.DisplayCollectionsView()
	case userconfiguration.FieldEnabledLocalPassword:
		return m.EnabledLocalPassword()
	case userconfiguration.FieldHidePlayedInLatest:
		return m.HidePlayedInLatest()
	case userconfiguration.FieldRememberAudioSelections:
		return m.RememberAudioSelections()
	case userconfiguration.FieldEnableNextEpisodeAutoPlay:
		return m.EnableNextEpisodeAutoPlay()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserConfigurationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userconfiguration.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case userconfiguration.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case userconfiguration.FieldCastReceiverID:
		return m.OldCastReceiverID(ctx)
	case userconfiguration.FieldAudioLanguagePreference:
		return m.OldAudioLanguagePreference(ctx)
	case userconfiguration.FieldPlayDefaultAudioTrack:
		return m.OldPlayDefaultAudioTrack(ctx)
	case userconfiguration.FieldSubtitleLanguagePreference:
		return m.OldSubtitleLanguagePreference(ctx)
	case userconfiguration.FieldSubtitleMode:
		return m.OldSubtitleMode(ctx)
	case userconfiguration.FieldGropuedFolders:
		return m.OldGropuedFolders(ctx)
	case userconfiguration.FieldOrderedViews:
		return m.OldOrderedViews(ctx)
	case userconfiguration.FieldLatestItemsExcludes:
		return m.OldLatestItemsExcludes(ctx)
	case userconfiguration.FieldMyMediaExcludes:
		return m.OldMyMediaExcludes(ctx)
	case userconfiguration.FieldDisplayMissingEpisodes:
		return m.OldDisplayMissingEpisodes(ctx)
	case userconfiguration.FieldDisplayCollectionsView:
		return m.OldDisplayCollectionsView(ctx)
	case userconfiguration.FieldEnabledLocalPassword:
		return m.OldEnabledLocalPassword(ctx)
	case userconfiguration.FieldHidePlayedInLatest:
		return m.OldHidePlayedInLatest(ctx)
	case userconfiguration.FieldRememberAudioSelections:
		return m.OldRememberAudioSelections(ctx)
	case userconfiguration.FieldEnableNextEpisodeAutoPlay:
		return m.OldEnableNextEpisodeAutoPlay(ctx)
	}
	return nil, fmt.Errorf("unknown UserConfiguration field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserConfigurationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userconfiguration.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case userconfiguration.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case userconfiguration.FieldCastReceiverID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCastReceiverID(v)
		return nil
	case userconfiguration.FieldAudioLanguagePreference:
		v, ok := value.(userconfiguration.AudioLanguagePreference)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAudioLanguagePreference(v)
		return nil
	case userconfiguration.FieldPlayDefaultAudioTrack:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlayDefaultAudioTrack(v)
		return nil
	case userconfiguration.FieldSubtitleLanguagePreference:
		v, ok := value.(userconfiguration.SubtitleLanguagePreference)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubtitleLanguagePreference(v)
		return nil
	case userconfiguration.FieldSubtitleMode:
		v, ok := value.(userconfiguration.SubtitleMode)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubtitleMode(v)
		return nil
	case userconfiguration.FieldGropuedFolders:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGropuedFolders(v)
		return nil
	case userconfiguration.FieldOrderedViews:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderedViews(v)
		return nil
	case userconfiguration.FieldLatestItemsExcludes:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLatestItemsExcludes(v)
		return nil
	case userconfiguration.FieldMyMediaExcludes:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMyMediaExcludes(v)
		return nil
	case userconfiguration.FieldDisplayMissingEpisodes:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDisplayMissingEpisodes(v)
		return nil
	case userconfiguration.FieldDisplayCollectionsView:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDisplayCollectionsView(v)
		return nil
	case userconfiguration.FieldEnabledLocalPassword:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabledLocalPassword(v)
		return nil
	case userconfiguration.FieldHidePlayedInLatest:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHidePlayedInLatest(v)
		return nil
	case userconfiguration.FieldRememberAudioSelections:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRememberAudioSelections(v)
		return nil
	case userconfiguration.FieldEnableNextEpisodeAutoPlay:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnableNextEpisodeAutoPlay(v)
		return nil
	}
	return fmt.Errorf("unknown UserConfiguration field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserConfigurationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserConfigurationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserConfigurationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserConfiguration numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserConfigurationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserConfigurationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserConfigurationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserConfiguration nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserConfigurationMutation) ResetField(name string) error {
	switch name {
	case userconfiguration.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case userconfiguration.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case userconfiguration.FieldCastReceiverID:
		m.ResetCastReceiverID()
		return nil
	case userconfiguration.FieldAudioLanguagePreference:
		m.ResetAudioLanguagePreference()
		return nil
	case userconfiguration.FieldPlayDefaultAudioTrack:
		m.ResetPlayDefaultAudioTrack()
		return nil
	case userconfiguration.FieldSubtitleLanguagePreference:
		m.ResetSubtitleLanguagePreference()
		return nil
	case userconfiguration.FieldSubtitleMode:
		m.ResetSubtitleMode()
		return nil
	case userconfiguration.FieldGropuedFolders:
		m.ResetGropuedFolders()
		return nil
	case userconfiguration.FieldOrderedViews:
		m.ResetOrderedViews()
		return nil
	case userconfiguration.FieldLatestItemsExcludes:
		m.ResetLatestItemsExcludes()
		return nil
	case userconfiguration.FieldMyMediaExcludes:
		m.ResetMyMediaExcludes()
		return nil
	case userconfiguration.FieldDisplayMissingEpisodes:
		m.ResetDisplayMissingEpisodes()
		return nil
	case userconfiguration.FieldDisplayCollectionsView:
		m.ResetDisplayCollectionsView()
		return nil
	case userconfiguration.FieldEnabledLocalPassword:
		m.ResetEnabledLocalPassword()
		return nil
	case userconfiguration.FieldHidePlayedInLatest:
		m.ResetHidePlayedInLatest()
		return nil
	case userconfiguration.FieldRememberAudioSelections:
		m.ResetRememberAudioSelections()
		return nil
	case userconfiguration.FieldEnableNextEpisodeAutoPlay:
		m.ResetEnableNextEpisodeAutoPlay()
		return nil
	}
	return fmt.Errorf("unknown UserConfiguration field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserConfigurationMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.user != nil {
		edges = append(edges, userconfiguration.EdgeUser)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserConfigurationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case userconfiguration.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserConfigurationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserConfigurationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserConfigurationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleareduser {
		edges = append(edges, userconfiguration.EdgeUser)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserConfigurationMutation) EdgeCleared(name string) bool {
	switch name {
	case userconfiguration.EdgeUser:
		return m.cleareduser
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserConfigurationMutation) ClearEdge(name string) error {
	switch name {
	case userconfiguration.EdgeUser:
		m.ClearUser()
		return nil
	}
	return fmt.Errorf("unknown UserConfiguration unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserConfigurationMutation) ResetEdge(name string) error {
	switch name {
	case userconfiguration.EdgeUser:
		m.ResetUser()
		return nil
	}
	return fmt.Errorf("unknown UserConfiguration edge %s", name)
}
