// Code generated by ent, DO NOT EDIT.

package store

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/FreekingDean/gojellyfin/internal/store/playlist"
	"github.com/FreekingDean/gojellyfin/internal/store/playlistshare"
	"github.com/FreekingDean/gojellyfin/internal/store/user"
	"github.com/google/uuid"
)

// PlaylistShare is the model entity for the PlaylistShare schema.
type PlaylistShare struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PlaylistID holds the value of the "playlist_id" field.
	PlaylistID uuid.UUID `json:"playlist_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CanEdit holds the value of the "can_edit" field.
	CanEdit bool `json:"can_edit,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlaylistShareQuery when eager-loading is set.
	Edges        PlaylistShareEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlaylistShareEdges holds the relations/edges for other nodes in the graph.
type PlaylistShareEdges struct {
	// Playlist holds the value of the playlist edge.
	Playlist *Playlist `json:"playlist,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlaylistOrErr returns the Playlist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaylistShareEdges) PlaylistOrErr() (*Playlist, error) {
	if e.Playlist != nil {
		return e.Playlist, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: playlist.Label}
	}
	return nil, &NotLoadedError{edge: "playlist"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaylistShareEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlaylistShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playlistshare.FieldCanEdit:
			values[i] = new(sql.NullBool)
		case playlistshare.FieldCreatedAt, playlistshare.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case playlistshare.FieldID, playlistshare.FieldPlaylistID, playlistshare.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlaylistShare fields.
func (_m *PlaylistShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playlistshare.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case playlistshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case playlistshare.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case playlistshare.FieldPlaylistID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_id", values[i])
			} else if value != nil {
				_m.PlaylistID = *value
			}
		case playlistshare.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case playlistshare.FieldCanEdit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_edit", values[i])
			} else if value.Valid {
				_m.CanEdit = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlaylistShare.
// This includes values selected through modifiers, order, etc.
func (_m *PlaylistShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlaylist queries the "playlist" edge of the PlaylistShare entity.
func (_m *PlaylistShare) QueryPlaylist() *PlaylistQuery {
	return NewPlaylistShareClient(_m.config).QueryPlaylist(_m)
}

// QueryUser queries the "user" edge of the PlaylistShare entity.
func (_m *PlaylistShare) QueryUser() *UserQuery {
	return NewPlaylistShareClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PlaylistShare.
// Note that you need to call PlaylistShare.Unwrap() before calling this method if this PlaylistShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlaylistShare) Update() *PlaylistShareUpdateOne {
	return NewPlaylistShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlaylistShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlaylistShare) Unwrap() *PlaylistShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("store: PlaylistShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlaylistShare) String() string {
	var builder strings.Builder
	builder.WriteString("PlaylistShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("playlist_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaylistID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("can_edit=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanEdit))
	builder.WriteByte(')')
	return builder.String()
}

// PlaylistShares is a parsable slice of PlaylistShare.
type PlaylistShares []*PlaylistShare
