



// Code generated by ent, DO NOT EDIT.



package store



import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/FreekingDean/gojellyfin/internal/store/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)


import (
	 "github.com/FreekingDean/gojellyfin/internal/store/playlistentry"
)





// PlaylistEntryDelete is the builder for deleting a PlaylistEntry entity.
type PlaylistEntryDelete struct {
	config
	hooks      []Hook
	mutation   *PlaylistEntryMutation
}

// Where appends a list predicates to the PlaylistEntryDelete builder.
func (_d *PlaylistEntryDelete) Where(ps ...predicate.PlaylistEntry) *PlaylistEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlaylistEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlaylistEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}


	
	




func (_d *PlaylistEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(playlistentry.Table, sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}







// PlaylistEntryDeleteOne is the builder for deleting a single PlaylistEntry entity.
type PlaylistEntryDeleteOne struct {
	_d *PlaylistEntryDelete
}

// Where appends a list predicates to the PlaylistEntryDelete builder.
func (_d *PlaylistEntryDeleteOne) Where(ps ...predicate.PlaylistEntry) *PlaylistEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlaylistEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ playlistentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlaylistEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}

