// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/item"
	"github.com/FreekingDean/gojellyfin/internal/store/playlist"
	"github.com/FreekingDean/gojellyfin/internal/store/playlistentry"
	"github.com/FreekingDean/gojellyfin/internal/store/playlistshare"
	"github.com/FreekingDean/gojellyfin/internal/store/predicate"
	"github.com/FreekingDean/gojellyfin/internal/store/user"
	"github.com/google/uuid"
)

// PlaylistUpdate is the builder for updating Playlist entities.
type PlaylistUpdate struct {
	config
	hooks    []Hook
	mutation *PlaylistMutation
}

// Where appends a list predicates to the PlaylistUpdate builder.
func (_u *PlaylistUpdate) Where(ps ...predicate.Playlist) *PlaylistUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistUpdate) SetCreatedAt(v time.Time) *PlaylistUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableCreatedAt(v *time.Time) *PlaylistUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlaylistUpdate) SetUpdatedAt(v time.Time) *PlaylistUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *PlaylistUpdate) SetItemID(v uuid.UUID) *PlaylistUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableItemID(v *uuid.UUID) *PlaylistUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PlaylistUpdate) SetOwnerID(v uuid.UUID) *PlaylistUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableOwnerID(v *uuid.UUID) *PlaylistUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetOpenAccess sets the "open_access" field.
func (_u *PlaylistUpdate) SetOpenAccess(v bool) *PlaylistUpdate {
	_u.mutation.SetOpenAccess(v)
	return _u
}

// SetNillableOpenAccess sets the "open_access" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableOpenAccess(v *bool) *PlaylistUpdate {
	if v != nil {
		_u.SetOpenAccess(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *PlaylistUpdate) SetItem(v *Item) *PlaylistUpdate {
	return _u.SetItemID(v.ID)
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PlaylistUpdate) SetOwner(v *User) *PlaylistUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the PlaylistEntry entity by IDs.
func (_u *PlaylistUpdate) AddEntryIDs(ids ...uuid.UUID) *PlaylistUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the PlaylistEntry entity.
func (_u *PlaylistUpdate) AddEntries(v ...*PlaylistEntry) *PlaylistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the PlaylistShare entity by IDs.
func (_u *PlaylistUpdate) AddShareIDs(ids ...uuid.UUID) *PlaylistUpdate {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the PlaylistShare entity.
func (_u *PlaylistUpdate) AddShares(v ...*PlaylistShare) *PlaylistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// Mutation returns the PlaylistMutation object of the builder.
func (_u *PlaylistUpdate) Mutation() *PlaylistMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *PlaylistUpdate) ClearItem() *PlaylistUpdate {
	_u.mutation.ClearItem()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PlaylistUpdate) ClearOwner() *PlaylistUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearEntries clears all "entries" edges to the PlaylistEntry entity.
func (_u *PlaylistUpdate) ClearEntries() *PlaylistUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to PlaylistEntry entities by IDs.
func (_u *PlaylistUpdate) RemoveEntryIDs(ids ...uuid.UUID) *PlaylistUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to PlaylistEntry entities.
func (_u *PlaylistUpdate) RemoveEntries(v ...*PlaylistEntry) *PlaylistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearShares clears all "shares" edges to the PlaylistShare entity.
func (_u *PlaylistUpdate) ClearShares() *PlaylistUpdate {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to PlaylistShare entities by IDs.
func (_u *PlaylistUpdate) RemoveShareIDs(ids ...uuid.UUID) *PlaylistUpdate {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to PlaylistShare entities.
func (_u *PlaylistUpdate) RemoveShares(v ...*PlaylistShare) *PlaylistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlaylistUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlaylistUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlaylistUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := playlist.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistUpdate) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "Playlist.item"`)
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "Playlist.owner"`)
	}
	return nil
}

func (_u *PlaylistUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlist.Table, playlist.Columns, sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(playlist.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OpenAccess(); ok {
		_spec.SetField(playlist.FieldOpenAccess, field.TypeBool, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   playlist.ItemTable,
			Columns: []string{playlist.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   playlist.ItemTable,
			Columns: []string{playlist.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlist.OwnerTable,
			Columns: []string{playlist.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlist.OwnerTable,
			Columns: []string{playlist.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlaylistUpdateOne is the builder for updating a single Playlist entity.
type PlaylistUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaylistMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistUpdateOne) SetCreatedAt(v time.Time) *PlaylistUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableCreatedAt(v *time.Time) *PlaylistUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlaylistUpdateOne) SetUpdatedAt(v time.Time) *PlaylistUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *PlaylistUpdateOne) SetItemID(v uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableItemID(v *uuid.UUID) *PlaylistUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PlaylistUpdateOne) SetOwnerID(v uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableOwnerID(v *uuid.UUID) *PlaylistUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetOpenAccess sets the "open_access" field.
func (_u *PlaylistUpdateOne) SetOpenAccess(v bool) *PlaylistUpdateOne {
	_u.mutation.SetOpenAccess(v)
	return _u
}

// SetNillableOpenAccess sets the "open_access" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableOpenAccess(v *bool) *PlaylistUpdateOne {
	if v != nil {
		_u.SetOpenAccess(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *PlaylistUpdateOne) SetItem(v *Item) *PlaylistUpdateOne {
	return _u.SetItemID(v.ID)
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PlaylistUpdateOne) SetOwner(v *User) *PlaylistUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the PlaylistEntry entity by IDs.
func (_u *PlaylistUpdateOne) AddEntryIDs(ids ...uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the PlaylistEntry entity.
func (_u *PlaylistUpdateOne) AddEntries(v ...*PlaylistEntry) *PlaylistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the PlaylistShare entity by IDs.
func (_u *PlaylistUpdateOne) AddShareIDs(ids ...uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the PlaylistShare entity.
func (_u *PlaylistUpdateOne) AddShares(v ...*PlaylistShare) *PlaylistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// Mutation returns the PlaylistMutation object of the builder.
func (_u *PlaylistUpdateOne) Mutation() *PlaylistMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *PlaylistUpdateOne) ClearItem() *PlaylistUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PlaylistUpdateOne) ClearOwner() *PlaylistUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearEntries clears all "entries" edges to the PlaylistEntry entity.
func (_u *PlaylistUpdateOne) ClearEntries() *PlaylistUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to PlaylistEntry entities by IDs.
func (_u *PlaylistUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to PlaylistEntry entities.
func (_u *PlaylistUpdateOne) RemoveEntries(v ...*PlaylistEntry) *PlaylistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearShares clears all "shares" edges to the PlaylistShare entity.
func (_u *PlaylistUpdateOne) ClearShares() *PlaylistUpdateOne {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to PlaylistShare entities by IDs.
func (_u *PlaylistUpdateOne) RemoveShareIDs(ids ...uuid.UUID) *PlaylistUpdateOne {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to PlaylistShare entities.
func (_u *PlaylistUpdateOne) RemoveShares(v ...*PlaylistShare) *PlaylistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// Where appends a list predicates to the PlaylistUpdate builder.
func (_u *PlaylistUpdateOne) Where(ps ...predicate.Playlist) *PlaylistUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlaylistUpdateOne) Select(field string, fields ...string) *PlaylistUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Playlist entity.
func (_u *PlaylistUpdateOne) Save(ctx context.Context) (*Playlist, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistUpdateOne) SaveX(ctx context.Context) *Playlist {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlaylistUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlaylistUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := playlist.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistUpdateOne) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "Playlist.item"`)
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`store: clearing a required unique edge "Playlist.owner"`)
	}
	return nil
}

func (_u *PlaylistUpdateOne) sqlSave(ctx context.Context) (_node *Playlist, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlist.Table, playlist.Columns, sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`store: missing "Playlist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playlist.FieldID)
		for _, f := range fields {
			if !playlist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("store: invalid field %q for query", f)}
			}
			if f != playlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(playlist.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OpenAccess(); ok {
		_spec.SetField(playlist.FieldOpenAccess, field.TypeBool, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   playlist.ItemTable,
			Columns: []string{playlist.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   playlist.ItemTable,
			Columns: []string{playlist.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlist.OwnerTable,
			Columns: []string{playlist.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlist.OwnerTable,
			Columns: []string{playlist.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.EntriesTable,
			Columns: []string{playlist.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlist.SharesTable,
			Columns: []string{playlist.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Playlist{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
