// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/predicate"
	"github.com/FreekingDean/gojellyfin/internal/store/quickconnectrequest"
)

// QuickConnectRequestDelete is the builder for deleting a QuickConnectRequest entity.
type QuickConnectRequestDelete struct {
	config
	hooks    []Hook
	mutation *QuickConnectRequestMutation
}

// Where appends a list predicates to the QuickConnectRequestDelete builder.
func (_d *QuickConnectRequestDelete) Where(ps ...predicate.QuickConnectRequest) *QuickConnectRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuickConnectRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuickConnectRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuickConnectRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quickconnectrequest.Table, sqlgraph.NewFieldSpec(quickconnectrequest.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuickConnectRequestDeleteOne is the builder for deleting a single QuickConnectRequest entity.
type QuickConnectRequestDeleteOne struct {
	_d *QuickConnectRequestDelete
}

// Where appends a list predicates to the QuickConnectRequestDelete builder.
func (_d *QuickConnectRequestDeleteOne) Where(ps ...predicate.QuickConnectRequest) *QuickConnectRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuickConnectRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quickconnectrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuickConnectRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
