// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/itemsource"
	"github.com/FreekingDean/gojellyfin/internal/store/librarysource"
	"github.com/FreekingDean/gojellyfin/internal/store/source"
	"github.com/google/uuid"
)

// SourceCreate is the builder for creating a Source entity.
type SourceCreate struct {
	config
	mutation *SourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SourceCreate) SetCreatedAt(v time.Time) *SourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableCreatedAt(v *time.Time) *SourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SourceCreate) SetUpdatedAt(v time.Time) *SourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableUpdatedAt(v *time.Time) *SourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SourceCreate) SetName(v string) *SourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *SourceCreate) SetURL(v string) *SourceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetAPIKeyVariable sets the "api_key_variable" field.
func (_c *SourceCreate) SetAPIKeyVariable(v string) *SourceCreate {
	_c.mutation.SetAPIKeyVariable(v)
	return _c
}

// SetRootPath sets the "root_path" field.
func (_c *SourceCreate) SetRootPath(v string) *SourceCreate {
	_c.mutation.SetRootPath(v)
	return _c
}

// SetNillableRootPath sets the "root_path" field if the given value is not nil.
func (_c *SourceCreate) SetNillableRootPath(v *string) *SourceCreate {
	if v != nil {
		_c.SetRootPath(*v)
	}
	return _c
}

// SetLocalPath sets the "local_path" field.
func (_c *SourceCreate) SetLocalPath(v string) *SourceCreate {
	_c.mutation.SetLocalPath(v)
	return _c
}

// SetNillableLocalPath sets the "local_path" field if the given value is not nil.
func (_c *SourceCreate) SetNillableLocalPath(v *string) *SourceCreate {
	if v != nil {
		_c.SetLocalPath(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *SourceCreate) SetKind(v source.Kind) *SourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SourceCreate) SetID(v uuid.UUID) *SourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddLibraryIDs adds the "libraries" edge to the LibrarySource entity by IDs.
func (_c *SourceCreate) AddLibraryIDs(ids ...uuid.UUID) *SourceCreate {
	_c.mutation.AddLibraryIDs(ids...)
	return _c
}

// AddLibraries adds the "libraries" edges to the LibrarySource entity.
func (_c *SourceCreate) AddLibraries(v ...*LibrarySource) *SourceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLibraryIDs(ids...)
}

// AddFileIDs adds the "files" edge to the ItemSource entity by IDs.
func (_c *SourceCreate) AddFileIDs(ids ...uuid.UUID) *SourceCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the ItemSource entity.
func (_c *SourceCreate) AddFiles(v ...*ItemSource) *SourceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_c *SourceCreate) Mutation() *SourceMutation {
	return _c.mutation
}

// Save creates the Source in the database.
func (_c *SourceCreate) Save(ctx context.Context) (*Source, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceCreate) SaveX(ctx context.Context) *Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := source.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := source.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`store: missing required field "Source.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`store: missing required field "Source.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`store: missing required field "Source.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`store: missing required field "Source.url"`)}
	}
	if _, ok := _c.mutation.APIKeyVariable(); !ok {
		return &ValidationError{Name: "api_key_variable", err: errors.New(`store: missing required field "Source.api_key_variable"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`store: missing required field "Source.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := source.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`store: validator failed for field "Source.kind": %w`, err)}
		}
	}
	return nil
}

func (_c *SourceCreate) sqlSave(ctx context.Context) (*Source, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceCreate) createSpec() (*Source, *sqlgraph.CreateSpec) {
	var (
		_node = &Source{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(source.Table, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(source.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.APIKeyVariable(); ok {
		_spec.SetField(source.FieldAPIKeyVariable, field.TypeString, value)
		_node.APIKeyVariable = value
	}
	if value, ok := _c.mutation.RootPath(); ok {
		_spec.SetField(source.FieldRootPath, field.TypeString, value)
		_node.RootPath = value
	}
	if value, ok := _c.mutation.LocalPath(); ok {
		_spec.SetField(source.FieldLocalPath, field.TypeString, value)
		_node.LocalPath = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(source.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if nodes := _c.mutation.LibrariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.LibrariesTable,
			Columns: []string{source.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(librarysource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.FilesTable,
			Columns: []string{source.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemsource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Source.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceCreate) OnConflict(opts ...sql.ConflictOption) *SourceUpsertOne {
	_c.conflict = opts
	return &SourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Source.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceCreate) OnConflictColumns(columns ...string) *SourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceUpsertOne{
		create: _c,
	}
}

type (
	// SourceUpsertOne is the builder for "upsert"-ing
	//  one Source node.
	SourceUpsertOne struct {
		create *SourceCreate
	}

	// SourceUpsert is the "OnConflict" setter.
	SourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *SourceUpsert) SetCreatedAt(v time.Time) *SourceUpsert {
	u.Set(source.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SourceUpsert) UpdateCreatedAt() *SourceUpsert {
	u.SetExcluded(source.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceUpsert) SetUpdatedAt(v time.Time) *SourceUpsert {
	u.Set(source.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceUpsert) UpdateUpdatedAt() *SourceUpsert {
	u.SetExcluded(source.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *SourceUpsert) SetName(v string) *SourceUpsert {
	u.Set(source.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SourceUpsert) UpdateName() *SourceUpsert {
	u.SetExcluded(source.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *SourceUpsert) SetURL(v string) *SourceUpsert {
	u.Set(source.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SourceUpsert) UpdateURL() *SourceUpsert {
	u.SetExcluded(source.FieldURL)
	return u
}

// SetAPIKeyVariable sets the "api_key_variable" field.
func (u *SourceUpsert) SetAPIKeyVariable(v string) *SourceUpsert {
	u.Set(source.FieldAPIKeyVariable, v)
	return u
}

// UpdateAPIKeyVariable sets the "api_key_variable" field to the value that was provided on create.
func (u *SourceUpsert) UpdateAPIKeyVariable() *SourceUpsert {
	u.SetExcluded(source.FieldAPIKeyVariable)
	return u
}

// SetRootPath sets the "root_path" field.
func (u *SourceUpsert) SetRootPath(v string) *SourceUpsert {
	u.Set(source.FieldRootPath, v)
	return u
}

// UpdateRootPath sets the "root_path" field to the value that was provided on create.
func (u *SourceUpsert) UpdateRootPath() *SourceUpsert {
	u.SetExcluded(source.FieldRootPath)
	return u
}

// ClearRootPath clears the value of the "root_path" field.
func (u *SourceUpsert) ClearRootPath() *SourceUpsert {
	u.SetNull(source.FieldRootPath)
	return u
}

// SetLocalPath sets the "local_path" field.
func (u *SourceUpsert) SetLocalPath(v string) *SourceUpsert {
	u.Set(source.FieldLocalPath, v)
	return u
}

// UpdateLocalPath sets the "local_path" field to the value that was provided on create.
func (u *SourceUpsert) UpdateLocalPath() *SourceUpsert {
	u.SetExcluded(source.FieldLocalPath)
	return u
}

// ClearLocalPath clears the value of the "local_path" field.
func (u *SourceUpsert) ClearLocalPath() *SourceUpsert {
	u.SetNull(source.FieldLocalPath)
	return u
}

// SetKind sets the "kind" field.
func (u *SourceUpsert) SetKind(v source.Kind) *SourceUpsert {
	u.Set(source.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SourceUpsert) UpdateKind() *SourceUpsert {
	u.SetExcluded(source.FieldKind)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Source.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(source.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceUpsertOne) UpdateNewValues() *SourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(source.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Source.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SourceUpsertOne) Ignore() *SourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceUpsertOne) DoNothing() *SourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceCreate.OnConflict
// documentation for more info.
func (u *SourceUpsertOne) Update(set func(*SourceUpsert)) *SourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SourceUpsertOne) SetCreatedAt(v time.Time) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateCreatedAt() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceUpsertOne) SetUpdatedAt(v time.Time) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateUpdatedAt() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SourceUpsertOne) SetName(v string) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateName() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *SourceUpsertOne) SetURL(v string) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateURL() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateURL()
	})
}

// SetAPIKeyVariable sets the "api_key_variable" field.
func (u *SourceUpsertOne) SetAPIKeyVariable(v string) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetAPIKeyVariable(v)
	})
}

// UpdateAPIKeyVariable sets the "api_key_variable" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateAPIKeyVariable() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateAPIKeyVariable()
	})
}

// SetRootPath sets the "root_path" field.
func (u *SourceUpsertOne) SetRootPath(v string) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetRootPath(v)
	})
}

// UpdateRootPath sets the "root_path" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateRootPath() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateRootPath()
	})
}

// ClearRootPath clears the value of the "root_path" field.
func (u *SourceUpsertOne) ClearRootPath() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.ClearRootPath()
	})
}

// SetLocalPath sets the "local_path" field.
func (u *SourceUpsertOne) SetLocalPath(v string) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetLocalPath(v)
	})
}

// UpdateLocalPath sets the "local_path" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateLocalPath() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateLocalPath()
	})
}

// ClearLocalPath clears the value of the "local_path" field.
func (u *SourceUpsertOne) ClearLocalPath() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.ClearLocalPath()
	})
}

// SetKind sets the "kind" field.
func (u *SourceUpsertOne) SetKind(v source.Kind) *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SourceUpsertOne) UpdateKind() *SourceUpsertOne {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateKind()
	})
}

// Exec executes the query.
func (u *SourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for SourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SourceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("store: SourceUpsertOne.ID is not supported by MySQL driver. Use SourceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SourceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SourceCreateBulk is the builder for creating many Source entities in bulk.
type SourceCreateBulk struct {
	config
	err      error
	builders []*SourceCreate
	conflict []sql.ConflictOption
}

// Save creates the Source entities in the database.
func (_c *SourceCreateBulk) Save(ctx context.Context) ([]*Source, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Source, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceCreateBulk) SaveX(ctx context.Context) []*Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Source.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *SourceUpsertBulk {
	_c.conflict = opts
	return &SourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Source.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceCreateBulk) OnConflictColumns(columns ...string) *SourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceUpsertBulk{
		create: _c,
	}
}

// SourceUpsertBulk is the builder for "upsert"-ing
// a bulk of Source nodes.
type SourceUpsertBulk struct {
	create *SourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Source.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(source.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceUpsertBulk) UpdateNewValues() *SourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(source.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Source.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SourceUpsertBulk) Ignore() *SourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceUpsertBulk) DoNothing() *SourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceCreateBulk.OnConflict
// documentation for more info.
func (u *SourceUpsertBulk) Update(set func(*SourceUpsert)) *SourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SourceUpsertBulk) SetCreatedAt(v time.Time) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateCreatedAt() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceUpsertBulk) SetUpdatedAt(v time.Time) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateUpdatedAt() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SourceUpsertBulk) SetName(v string) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateName() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *SourceUpsertBulk) SetURL(v string) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateURL() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateURL()
	})
}

// SetAPIKeyVariable sets the "api_key_variable" field.
func (u *SourceUpsertBulk) SetAPIKeyVariable(v string) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetAPIKeyVariable(v)
	})
}

// UpdateAPIKeyVariable sets the "api_key_variable" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateAPIKeyVariable() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateAPIKeyVariable()
	})
}

// SetRootPath sets the "root_path" field.
func (u *SourceUpsertBulk) SetRootPath(v string) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetRootPath(v)
	})
}

// UpdateRootPath sets the "root_path" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateRootPath() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateRootPath()
	})
}

// ClearRootPath clears the value of the "root_path" field.
func (u *SourceUpsertBulk) ClearRootPath() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.ClearRootPath()
	})
}

// SetLocalPath sets the "local_path" field.
func (u *SourceUpsertBulk) SetLocalPath(v string) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetLocalPath(v)
	})
}

// UpdateLocalPath sets the "local_path" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateLocalPath() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateLocalPath()
	})
}

// ClearLocalPath clears the value of the "local_path" field.
func (u *SourceUpsertBulk) ClearLocalPath() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.ClearLocalPath()
	})
}

// SetKind sets the "kind" field.
func (u *SourceUpsertBulk) SetKind(v source.Kind) *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SourceUpsertBulk) UpdateKind() *SourceUpsertBulk {
	return u.Update(func(s *SourceUpsert) {
		s.UpdateKind()
	})
}

// Exec executes the query.
func (u *SourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("store: OnConflict was set for builder %d. Set it on the SourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for SourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
