// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FreekingDean/gojellyfin/internal/store/session"
	"github.com/FreekingDean/gojellyfin/internal/store/syncplaygroup"
	"github.com/FreekingDean/gojellyfin/internal/store/syncplaygroupmember"
	"github.com/google/uuid"
)

// SyncPlayGroupMemberCreate is the builder for creating a SyncPlayGroupMember entity.
type SyncPlayGroupMemberCreate struct {
	config
	mutation *SyncPlayGroupMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncPlayGroupMemberCreate) SetCreatedAt(v time.Time) *SyncPlayGroupMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncPlayGroupMemberCreate) SetNillableCreatedAt(v *time.Time) *SyncPlayGroupMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SyncPlayGroupMemberCreate) SetUpdatedAt(v time.Time) *SyncPlayGroupMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SyncPlayGroupMemberCreate) SetNillableUpdatedAt(v *time.Time) *SyncPlayGroupMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SyncPlayGroupMemberCreate) SetGroupID(v uuid.UUID) *SyncPlayGroupMemberCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *SyncPlayGroupMemberCreate) SetSessionID(v uuid.UUID) *SyncPlayGroupMemberCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SyncPlayGroupMemberCreate) SetID(v uuid.UUID) *SyncPlayGroupMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the SyncPlayGroup entity.
func (_c *SyncPlayGroupMemberCreate) SetGroup(v *SyncPlayGroup) *SyncPlayGroupMemberCreate {
	return _c.SetGroupID(v.ID)
}

// SetSession sets the "session" edge to the Session entity.
func (_c *SyncPlayGroupMemberCreate) SetSession(v *Session) *SyncPlayGroupMemberCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the SyncPlayGroupMemberMutation object of the builder.
func (_c *SyncPlayGroupMemberCreate) Mutation() *SyncPlayGroupMemberMutation {
	return _c.mutation
}

// Save creates the SyncPlayGroupMember in the database.
func (_c *SyncPlayGroupMemberCreate) Save(ctx context.Context) (*SyncPlayGroupMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncPlayGroupMemberCreate) SaveX(ctx context.Context) *SyncPlayGroupMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncPlayGroupMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncPlayGroupMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncPlayGroupMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := syncplaygroupmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := syncplaygroupmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncPlayGroupMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`store: missing required field "SyncPlayGroupMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`store: missing required field "SyncPlayGroupMember.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`store: missing required field "SyncPlayGroupMember.group_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`store: missing required field "SyncPlayGroupMember.session_id"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`store: missing required edge "SyncPlayGroupMember.group"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`store: missing required edge "SyncPlayGroupMember.session"`)}
	}
	return nil
}

func (_c *SyncPlayGroupMemberCreate) sqlSave(ctx context.Context) (*SyncPlayGroupMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncPlayGroupMemberCreate) createSpec() (*SyncPlayGroupMember, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncPlayGroupMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncplaygroupmember.Table, sqlgraph.NewFieldSpec(syncplaygroupmember.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(syncplaygroupmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(syncplaygroupmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncplaygroupmember.GroupTable,
			Columns: []string{syncplaygroupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncplaygroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncplaygroupmember.SessionTable,
			Columns: []string{syncplaygroupmember.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SyncPlayGroupMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SyncPlayGroupMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SyncPlayGroupMemberCreate) OnConflict(opts ...sql.ConflictOption) *SyncPlayGroupMemberUpsertOne {
	_c.conflict = opts
	return &SyncPlayGroupMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SyncPlayGroupMemberCreate) OnConflictColumns(columns ...string) *SyncPlayGroupMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SyncPlayGroupMemberUpsertOne{
		create: _c,
	}
}

type (
	// SyncPlayGroupMemberUpsertOne is the builder for "upsert"-ing
	//  one SyncPlayGroupMember node.
	SyncPlayGroupMemberUpsertOne struct {
		create *SyncPlayGroupMemberCreate
	}

	// SyncPlayGroupMemberUpsert is the "OnConflict" setter.
	SyncPlayGroupMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *SyncPlayGroupMemberUpsert) SetCreatedAt(v time.Time) *SyncPlayGroupMemberUpsert {
	u.Set(syncplaygroupmember.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsert) UpdateCreatedAt() *SyncPlayGroupMemberUpsert {
	u.SetExcluded(syncplaygroupmember.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncPlayGroupMemberUpsert) SetUpdatedAt(v time.Time) *SyncPlayGroupMemberUpsert {
	u.Set(syncplaygroupmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsert) UpdateUpdatedAt() *SyncPlayGroupMemberUpsert {
	u.SetExcluded(syncplaygroupmember.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SyncPlayGroupMemberUpsert) SetGroupID(v uuid.UUID) *SyncPlayGroupMemberUpsert {
	u.Set(syncplaygroupmember.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsert) UpdateGroupID() *SyncPlayGroupMemberUpsert {
	u.SetExcluded(syncplaygroupmember.FieldGroupID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *SyncPlayGroupMemberUpsert) SetSessionID(v uuid.UUID) *SyncPlayGroupMemberUpsert {
	u.Set(syncplaygroupmember.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsert) UpdateSessionID() *SyncPlayGroupMemberUpsert {
	u.SetExcluded(syncplaygroupmember.FieldSessionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(syncplaygroupmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SyncPlayGroupMemberUpsertOne) UpdateNewValues() *SyncPlayGroupMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(syncplaygroupmember.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SyncPlayGroupMemberUpsertOne) Ignore() *SyncPlayGroupMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SyncPlayGroupMemberUpsertOne) DoNothing() *SyncPlayGroupMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SyncPlayGroupMemberCreate.OnConflict
// documentation for more info.
func (u *SyncPlayGroupMemberUpsertOne) Update(set func(*SyncPlayGroupMemberUpsert)) *SyncPlayGroupMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SyncPlayGroupMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SyncPlayGroupMemberUpsertOne) SetCreatedAt(v time.Time) *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertOne) UpdateCreatedAt() *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncPlayGroupMemberUpsertOne) SetUpdatedAt(v time.Time) *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertOne) UpdateUpdatedAt() *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SyncPlayGroupMemberUpsertOne) SetGroupID(v uuid.UUID) *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertOne) UpdateGroupID() *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateGroupID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *SyncPlayGroupMemberUpsertOne) SetSessionID(v uuid.UUID) *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertOne) UpdateSessionID() *SyncPlayGroupMemberUpsertOne {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateSessionID()
	})
}

// Exec executes the query.
func (u *SyncPlayGroupMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for SyncPlayGroupMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SyncPlayGroupMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SyncPlayGroupMemberUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("store: SyncPlayGroupMemberUpsertOne.ID is not supported by MySQL driver. Use SyncPlayGroupMemberUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SyncPlayGroupMemberUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SyncPlayGroupMemberCreateBulk is the builder for creating many SyncPlayGroupMember entities in bulk.
type SyncPlayGroupMemberCreateBulk struct {
	config
	err      error
	builders []*SyncPlayGroupMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the SyncPlayGroupMember entities in the database.
func (_c *SyncPlayGroupMemberCreateBulk) Save(ctx context.Context) ([]*SyncPlayGroupMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncPlayGroupMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncPlayGroupMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncPlayGroupMemberCreateBulk) SaveX(ctx context.Context) []*SyncPlayGroupMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncPlayGroupMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncPlayGroupMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SyncPlayGroupMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SyncPlayGroupMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SyncPlayGroupMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *SyncPlayGroupMemberUpsertBulk {
	_c.conflict = opts
	return &SyncPlayGroupMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SyncPlayGroupMemberCreateBulk) OnConflictColumns(columns ...string) *SyncPlayGroupMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SyncPlayGroupMemberUpsertBulk{
		create: _c,
	}
}

// SyncPlayGroupMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of SyncPlayGroupMember nodes.
type SyncPlayGroupMemberUpsertBulk struct {
	create *SyncPlayGroupMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(syncplaygroupmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SyncPlayGroupMemberUpsertBulk) UpdateNewValues() *SyncPlayGroupMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(syncplaygroupmember.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SyncPlayGroupMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SyncPlayGroupMemberUpsertBulk) Ignore() *SyncPlayGroupMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SyncPlayGroupMemberUpsertBulk) DoNothing() *SyncPlayGroupMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SyncPlayGroupMemberCreateBulk.OnConflict
// documentation for more info.
func (u *SyncPlayGroupMemberUpsertBulk) Update(set func(*SyncPlayGroupMemberUpsert)) *SyncPlayGroupMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SyncPlayGroupMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SyncPlayGroupMemberUpsertBulk) SetCreatedAt(v time.Time) *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertBulk) UpdateCreatedAt() *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncPlayGroupMemberUpsertBulk) SetUpdatedAt(v time.Time) *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertBulk) UpdateUpdatedAt() *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SyncPlayGroupMemberUpsertBulk) SetGroupID(v uuid.UUID) *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertBulk) UpdateGroupID() *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateGroupID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *SyncPlayGroupMemberUpsertBulk) SetSessionID(v uuid.UUID) *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *SyncPlayGroupMemberUpsertBulk) UpdateSessionID() *SyncPlayGroupMemberUpsertBulk {
	return u.Update(func(s *SyncPlayGroupMemberUpsert) {
		s.UpdateSessionID()
	})
}

// Exec executes the query.
func (u *SyncPlayGroupMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("store: OnConflict was set for builder %d. Set it on the SyncPlayGroupMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("store: missing options for SyncPlayGroupMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SyncPlayGroupMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
