
// Code generated by ent, DO NOT EDIT.



	

package apikey




import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/FreekingDean/gojellyfin/internal/store/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)


const (
	// Label holds the string label denoting the apikey type in the database.
	Label = "api_key"
		// FieldID holds the string denoting the id field in the database.
		FieldID = "id"
		// FieldCreatedAt holds the string denoting the created_at field in the database.
		FieldCreatedAt = "created_at"
		// FieldUpdatedAt holds the string denoting the updated_at field in the database.
		FieldUpdatedAt = "updated_at"
		// FieldAccessToken holds the string denoting the access_token field in the database.
		FieldAccessToken = "access_token"
		// FieldAppName holds the string denoting the app_name field in the database.
		FieldAppName = "app_name"
		// FieldRevokedAt holds the string denoting the revoked_at field in the database.
		FieldRevokedAt = "revoked_at"
	// Table holds the table name of the apikey in the database.
	Table = "api_keys"

)



	
	// Columns holds all SQL columns for apikey fields.
	var Columns = []string{
			FieldID,
				FieldCreatedAt,
				FieldUpdatedAt,
				FieldAccessToken,
				FieldAppName,
				FieldRevokedAt,
	}
	
	

	





	
// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}









	var (
				// DefaultCreatedAt holds the default value on creation for the "created_at" field.
				DefaultCreatedAt func() time.Time
				// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
				DefaultUpdatedAt func() time.Time
				// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
				UpdateDefaultUpdatedAt func() time.Time
	)






// OrderOption defines the ordering options for the ApiKey queries.
type OrderOption func(*sql.Selector)

	
	
		// ByID orders the results by the id field.
		func ByID(opts ...sql.OrderTermOption) OrderOption {
			return sql.OrderByField(FieldID, opts...).ToFunc()
		}
	
			// ByCreatedAt orders the results by the created_at field.
			func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
			}
			// ByUpdatedAt orders the results by the updated_at field.
			func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
			}
			// ByAccessToken orders the results by the access_token field.
			func ByAccessToken(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldAccessToken, opts...).ToFunc()
			}
			// ByAppName orders the results by the app_name field.
			func ByAppName(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldAppName, opts...).ToFunc()
			}
			// ByRevokedAt orders the results by the revoked_at field.
			func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
			}







