// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/FreekingDean/gojellyfin/internal/store"
)

// The ActivityLogEntryFunc type is an adapter to allow the use of ordinary
// function as ActivityLogEntry mutator.
type ActivityLogEntryFunc func(context.Context, *store.ActivityLogEntryMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ActivityLogEntryFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ActivityLogEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ActivityLogEntryMutation", m)
}

// The ApiKeyFunc type is an adapter to allow the use of ordinary
// function as ApiKey mutator.
type ApiKeyFunc func(context.Context, *store.ApiKeyMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ApiKeyFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ApiKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ApiKeyMutation", m)
}

// The ChapterFunc type is an adapter to allow the use of ordinary
// function as Chapter mutator.
type ChapterFunc func(context.Context, *store.ChapterMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ChapterFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ChapterMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ChapterMutation", m)
}

// The ConfigurationFunc type is an adapter to allow the use of ordinary
// function as Configuration mutator.
type ConfigurationFunc func(context.Context, *store.ConfigurationMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ConfigurationFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ConfigurationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ConfigurationMutation", m)
}

// The CreditFunc type is an adapter to allow the use of ordinary
// function as Credit mutator.
type CreditFunc func(context.Context, *store.CreditMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f CreditFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.CreditMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.CreditMutation", m)
}

// The DeviceFunc type is an adapter to allow the use of ordinary
// function as Device mutator.
type DeviceFunc func(context.Context, *store.DeviceMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f DeviceFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.DeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.DeviceMutation", m)
}

// The DisplayPreferencesFunc type is an adapter to allow the use of ordinary
// function as DisplayPreferences mutator.
type DisplayPreferencesFunc func(context.Context, *store.DisplayPreferencesMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f DisplayPreferencesFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.DisplayPreferencesMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.DisplayPreferencesMutation", m)
}

// The GenreFunc type is an adapter to allow the use of ordinary
// function as Genre mutator.
type GenreFunc func(context.Context, *store.GenreMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f GenreFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.GenreMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.GenreMutation", m)
}

// The ImageFunc type is an adapter to allow the use of ordinary
// function as Image mutator.
type ImageFunc func(context.Context, *store.ImageMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ImageFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ImageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ImageMutation", m)
}

// The ImageBlobFunc type is an adapter to allow the use of ordinary
// function as ImageBlob mutator.
type ImageBlobFunc func(context.Context, *store.ImageBlobMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ImageBlobFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ImageBlobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ImageBlobMutation", m)
}

// The ItemFunc type is an adapter to allow the use of ordinary
// function as Item mutator.
type ItemFunc func(context.Context, *store.ItemMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ItemFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ItemMutation", m)
}

// The LibraryFunc type is an adapter to allow the use of ordinary
// function as Library mutator.
type LibraryFunc func(context.Context, *store.LibraryMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f LibraryFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.LibraryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.LibraryMutation", m)
}

// The LibraryOptionsFunc type is an adapter to allow the use of ordinary
// function as LibraryOptions mutator.
type LibraryOptionsFunc func(context.Context, *store.LibraryOptionsMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f LibraryOptionsFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.LibraryOptionsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.LibraryOptionsMutation", m)
}

// The ListingsProviderFunc type is an adapter to allow the use of ordinary
// function as ListingsProvider mutator.
type ListingsProviderFunc func(context.Context, *store.ListingsProviderMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f ListingsProviderFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.ListingsProviderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.ListingsProviderMutation", m)
}

// The MediaAttachmentFunc type is an adapter to allow the use of ordinary
// function as MediaAttachment mutator.
type MediaAttachmentFunc func(context.Context, *store.MediaAttachmentMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f MediaAttachmentFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.MediaAttachmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.MediaAttachmentMutation", m)
}

// The MediaSegmentFunc type is an adapter to allow the use of ordinary
// function as MediaSegment mutator.
type MediaSegmentFunc func(context.Context, *store.MediaSegmentMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f MediaSegmentFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.MediaSegmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.MediaSegmentMutation", m)
}

// The MediaSourceFunc type is an adapter to allow the use of ordinary
// function as MediaSource mutator.
type MediaSourceFunc func(context.Context, *store.MediaSourceMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f MediaSourceFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.MediaSourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.MediaSourceMutation", m)
}

// The MediaStreamFunc type is an adapter to allow the use of ordinary
// function as MediaStream mutator.
type MediaStreamFunc func(context.Context, *store.MediaStreamMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f MediaStreamFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.MediaStreamMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.MediaStreamMutation", m)
}

// The PersonFunc type is an adapter to allow the use of ordinary
// function as Person mutator.
type PersonFunc func(context.Context, *store.PersonMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f PersonFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.PersonMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.PersonMutation", m)
}

// The PlaylistFunc type is an adapter to allow the use of ordinary
// function as Playlist mutator.
type PlaylistFunc func(context.Context, *store.PlaylistMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f PlaylistFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.PlaylistMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.PlaylistMutation", m)
}

// The PlaylistEntryFunc type is an adapter to allow the use of ordinary
// function as PlaylistEntry mutator.
type PlaylistEntryFunc func(context.Context, *store.PlaylistEntryMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f PlaylistEntryFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.PlaylistEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.PlaylistEntryMutation", m)
}

// The PlaylistShareFunc type is an adapter to allow the use of ordinary
// function as PlaylistShare mutator.
type PlaylistShareFunc func(context.Context, *store.PlaylistShareMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f PlaylistShareFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.PlaylistShareMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.PlaylistShareMutation", m)
}

// The SeriesTimerFunc type is an adapter to allow the use of ordinary
// function as SeriesTimer mutator.
type SeriesTimerFunc func(context.Context, *store.SeriesTimerMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f SeriesTimerFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.SeriesTimerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.SeriesTimerMutation", m)
}

// The SessionFunc type is an adapter to allow the use of ordinary
// function as Session mutator.
type SessionFunc func(context.Context, *store.SessionMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f SessionFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.SessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.SessionMutation", m)
}

// The StudioFunc type is an adapter to allow the use of ordinary
// function as Studio mutator.
type StudioFunc func(context.Context, *store.StudioMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f StudioFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.StudioMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.StudioMutation", m)
}

// The TimerFunc type is an adapter to allow the use of ordinary
// function as Timer mutator.
type TimerFunc func(context.Context, *store.TimerMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f TimerFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.TimerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.TimerMutation", m)
}

// The TrickplayFunc type is an adapter to allow the use of ordinary
// function as Trickplay mutator.
type TrickplayFunc func(context.Context, *store.TrickplayMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f TrickplayFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.TrickplayMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.TrickplayMutation", m)
}

// The TunerHostFunc type is an adapter to allow the use of ordinary
// function as TunerHost mutator.
type TunerHostFunc func(context.Context, *store.TunerHostMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f TunerHostFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.TunerHostMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.TunerHostMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *store.UserMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.UserMutation", m)
}

// The UserConfigurationFunc type is an adapter to allow the use of ordinary
// function as UserConfiguration mutator.
type UserConfigurationFunc func(context.Context, *store.UserConfigurationMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f UserConfigurationFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.UserConfigurationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.UserConfigurationMutation", m)
}

// The UserItemDataFunc type is an adapter to allow the use of ordinary
// function as UserItemData mutator.
type UserItemDataFunc func(context.Context, *store.UserItemDataMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f UserItemDataFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.UserItemDataMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.UserItemDataMutation", m)
}

// The UserPolicyFunc type is an adapter to allow the use of ordinary
// function as UserPolicy mutator.
type UserPolicyFunc func(context.Context, *store.UserPolicyMutation) (store.Value, error)

// Mutate calls f(ctx, m).
func (f UserPolicyFunc) Mutate(ctx context.Context, m store.Mutation) (store.Value, error) {
	if mv, ok := m.(*store.UserPolicyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *store.UserPolicyMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, store.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m store.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m store.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m store.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op store.Op) Condition {
	return func(_ context.Context, m store.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m store.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m store.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m store.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk store.Hook, cond Condition) store.Hook {
	return func(next store.Mutator) store.Mutator {
		return store.MutateFunc(func(ctx context.Context, m store.Mutation) (store.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, store.Delete|store.Create)
func On(hk store.Hook, op store.Op) store.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, store.Update|store.UpdateOne)
func Unless(hk store.Hook, op store.Op) store.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) store.Hook {
	return func(store.Mutator) store.Mutator {
		return store.MutateFunc(func(context.Context, store.Mutation) (store.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []store.Hook {
//		return []store.Hook{
//			Reject(store.Delete|store.Update),
//		}
//	}
func Reject(op store.Op) store.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []store.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...store.Hook) Chain {
	return Chain{append([]store.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() store.Hook {
	return func(mutator store.Mutator) store.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...store.Hook) Chain {
	newHooks := make([]store.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
